In [1]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [2]:
filenames = []
for file in os.listdir('Documents'):
    filenames.append(os.path.join('Documents',file))

In [3]:
filenames[0:5]

['Documents\\1001349.yaml',
 'Documents\\1001351.yaml',
 'Documents\\1001353.yaml',
 'Documents\\1004729.yaml',
 'Documents\\1007655.yaml']

In [4]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = final_df.append(df)
        counter+=1
        
final_df

  0%|                                                                                         | 0/2590 [00:00<?, ?it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|                                                                                 | 1/2590 [00:00<27:44,  1.56it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|                                                                                 | 2/2590 [00:01<21:34,  2.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|                                                                                 | 3/2590 [00:01<20:15,  2.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▏                                                                                | 4/2590 [00:01<19:30,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▏                                                                                | 5/2590 [00:02<19:28,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▏                                                                                | 6/2590 [00:02<18:03,  2.38it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▏                                                                                | 7/2590 [00:03<18:50,  2.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▎                                                                                | 8/2590 [00:03<19:17,  2.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▎                                                                                | 9/2590 [00:04<19:15,  2.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▎                                                                               | 10/2590 [00:04<21:17,  2.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▎                                                                               | 11/2590 [00:05<19:43,  2.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  0%|▎                                                                               | 12/2590 [00:05<18:19,  2.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▍                                                                               | 13/2590 [00:05<19:12,  2.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▍                                                                               | 14/2590 [00:06<20:38,  2.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▍                                                                               | 15/2590 [00:07<21:57,  1.95it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▍                                                                               | 16/2590 [00:07<22:38,  1.89it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▌                                                                               | 17/2590 [00:08<23:35,  1.82it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▌                                                                               | 18/2590 [00:08<22:31,  1.90it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▌                                                                               | 19/2590 [00:09<22:05,  1.94it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▌                                                                               | 20/2590 [00:09<19:06,  2.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▋                                                                               | 21/2590 [00:09<19:23,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▋                                                                               | 22/2590 [00:10<20:52,  2.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▋                                                                               | 23/2590 [00:11<21:40,  1.97it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  1%|▋                                                                               | 24/2590 [00:11<20:45,  2.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▊                                                                               | 25/2590 [00:11<20:23,  2.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▊                                                                               | 26/2590 [00:12<18:59,  2.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▊                                                                               | 27/2590 [00:12<20:02,  2.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▊                                                                               | 28/2590 [00:13<20:00,  2.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▉                                                                               | 29/2590 [00:13<20:46,  2.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▉                                                                               | 30/2590 [00:14<21:03,  2.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▉                                                                               | 31/2590 [00:15<23:28,  1.82it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|▉                                                                               | 32/2590 [00:15<22:47,  1.87it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█                                                                               | 33/2590 [00:15<20:15,  2.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█                                                                               | 34/2590 [00:16<19:26,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█                                                                               | 35/2590 [00:16<19:28,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█                                                                               | 36/2590 [00:17<18:01,  2.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█▏                                                                              | 37/2590 [00:17<17:41,  2.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  1%|█▏                                                                              | 38/2590 [00:17<17:32,  2.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▏                                                                              | 39/2590 [00:18<18:26,  2.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▏                                                                              | 40/2590 [00:18<19:28,  2.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▎                                                                              | 41/2590 [00:19<20:49,  2.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▎                                                                              | 42/2590 [00:20<23:52,  1.78it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▎                                                                              | 43/2590 [00:20<25:11,  1.69it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▎                                                                              | 44/2590 [00:21<25:28,  1.67it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▍                                                                              | 45/2590 [00:21<24:05,  1.76it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▍                                                                              | 46/2590 [00:22<23:00,  1.84it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▍                                                                              | 47/2590 [00:22<22:11,  1.91it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  2%|█▍                                                                              | 48/2590 [00:23<20:55,  2.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▌                                                                              | 49/2590 [00:23<19:25,  2.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▌                                                                              | 50/2590 [00:24<18:59,  2.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▌                                                                              | 51/2590 [00:24<18:44,  2.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▌                                                                              | 52/2590 [00:25<19:07,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▋                                                                              | 53/2590 [00:25<16:12,  2.61it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▋                                                                              | 54/2590 [00:25<18:30,  2.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▋                                                                              | 55/2590 [00:26<18:28,  2.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▋                                                                              | 56/2590 [00:26<19:09,  2.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▊                                                                              | 57/2590 [00:27<19:18,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▊                                                                              | 58/2590 [00:27<20:45,  2.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▊                                                                              | 59/2590 [00:28<23:10,  1.82it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▊                                                                              | 60/2590 [00:29<23:04,  1.83it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▉                                                                              | 61/2590 [00:29<20:57,  2.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▉                                                                              | 62/2590 [00:29<21:43,  1.94it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▉                                                                              | 63/2590 [00:30<21:11,  1.99it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  2%|█▉                                                                              | 64/2590 [00:31<23:26,  1.80it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██                                                                              | 65/2590 [00:31<22:47,  1.85it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██                                                                              | 66/2590 [00:32<22:00,  1.91it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██                                                                              | 67/2590 [00:32<22:15,  1.89it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██                                                                              | 68/2590 [00:33<21:16,  1.98it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▏                                                                             | 69/2590 [00:33<17:30,  2.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▏                                                                             | 70/2590 [00:33<18:08,  2.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▏                                                                             | 71/2590 [00:34<18:43,  2.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  3%|██▏                                                                             | 72/2590 [00:34<18:59,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▎                                                                             | 73/2590 [00:35<21:33,  1.95it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▎                                                                             | 74/2590 [00:35<20:20,  2.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▎                                                                             | 75/2590 [00:36<20:44,  2.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▎                                                                             | 76/2590 [00:36<19:49,  2.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▍                                                                             | 77/2590 [00:37<18:33,  2.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▍                                                                             | 78/2590 [00:37<18:35,  2.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▍                                                                             | 79/2590 [00:38<18:23,  2.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▍                                                                             | 80/2590 [00:38<17:40,  2.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▌                                                                             | 81/2590 [00:38<17:51,  2.34it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▌                                                                             | 82/2590 [00:39<17:39,  2.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▌                                                                             | 83/2590 [00:39<17:16,  2.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▌                                                                             | 84/2590 [00:40<17:20,  2.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▋                                                                             | 85/2590 [00:40<17:23,  2.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▋                                                                             | 86/2590 [00:40<17:43,  2.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▋                                                                             | 87/2590 [00:41<18:24,  2.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▋                                                                             | 88/2590 [00:41<18:37,  2.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▋                                                                             | 89/2590 [00:42<18:47,  2.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  3%|██▊                                                                             | 90/2590 [00:42<17:23,  2.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▊                                                                             | 91/2590 [00:43<17:07,  2.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▊                                                                             | 92/2590 [00:43<17:14,  2.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▊                                                                             | 93/2590 [00:43<17:11,  2.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▉                                                                             | 94/2590 [00:44<17:44,  2.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▉                                                                             | 95/2590 [00:44<16:51,  2.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  4%|██▉                                                                             | 96/2590 [00:45<16:51,  2.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|██▉                                                                             | 97/2590 [00:45<14:26,  2.88it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███                                                                             | 98/2590 [00:45<16:05,  2.58it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███                                                                             | 99/2590 [00:46<16:20,  2.54it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███                                                                            | 100/2590 [00:46<18:28,  2.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███                                                                            | 101/2590 [00:47<18:13,  2.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███                                                                            | 102/2590 [00:47<17:40,  2.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▏                                                                           | 103/2590 [00:48<18:10,  2.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▏                                                                           | 104/2590 [00:48<17:47,  2.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▏                                                                           | 105/2590 [00:48<18:03,  2.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▏                                                                           | 106/2590 [00:49<19:41,  2.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▎                                                                           | 107/2590 [00:50<20:34,  2.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▎                                                                           | 108/2590 [00:50<20:53,  1.98it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▎                                                                           | 109/2590 [00:51<22:53,  1.81it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▎                                                                           | 110/2590 [00:51<25:01,  1.65it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▍                                                                           | 111/2590 [00:52<26:46,  1.54it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▍                                                                           | 112/2590 [00:53<26:07,  1.58it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▍                                                                           | 113/2590 [00:53<24:29,  1.69it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▍                                                                           | 114/2590 [00:54<24:36,  1.68it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▌                                                                           | 115/2590 [00:55<25:20,  1.63it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  4%|███▌                                                                           | 116/2590 [00:55<25:28,  1.62it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▌                                                                           | 117/2590 [00:56<24:46,  1.66it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▌                                                                           | 118/2590 [00:56<23:32,  1.75it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▋                                                                           | 119/2590 [00:57<23:55,  1.72it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  5%|███▋                                                                           | 120/2590 [00:57<20:21,  2.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▋                                                                           | 121/2590 [00:58<19:34,  2.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▋                                                                           | 122/2590 [00:58<18:47,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▊                                                                           | 123/2590 [00:59<19:45,  2.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▊                                                                           | 124/2590 [00:59<18:26,  2.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▊                                                                           | 125/2590 [00:59<18:43,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▊                                                                           | 126/2590 [01:00<18:26,  2.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▊                                                                           | 127/2590 [01:00<17:59,  2.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▉                                                                           | 128/2590 [01:01<17:16,  2.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▉                                                                           | 129/2590 [01:01<17:41,  2.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▉                                                                           | 130/2590 [01:02<18:15,  2.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|███▉                                                                           | 131/2590 [01:02<19:18,  2.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████                                                                           | 132/2590 [01:02<18:32,  2.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████                                                                           | 133/2590 [01:03<18:43,  2.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████                                                                           | 134/2590 [01:03<18:52,  2.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████                                                                           | 135/2590 [01:04<19:48,  2.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▏                                                                          | 136/2590 [01:05<22:07,  1.85it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▏                                                                          | 137/2590 [01:05<23:11,  1.76it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▏                                                                          | 138/2590 [01:06<23:02,  1.77it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▏                                                                          | 139/2590 [01:06<21:17,  1.92it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▎                                                                          | 140/2590 [01:07<20:55,  1.95it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▎                                                                          | 141/2590 [01:07<22:38,  1.80it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  5%|████▎                                                                          | 142/2590 [01:08<22:30,  1.81it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▎                                                                          | 143/2590 [01:09<24:05,  1.69it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  6%|████▍                                                                          | 144/2590 [01:09<24:15,  1.68it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▍                                                                          | 145/2590 [01:10<25:10,  1.62it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▍                                                                          | 146/2590 [01:11<27:38,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▍                                                                          | 147/2590 [01:11<28:31,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▌                                                                          | 148/2590 [01:14<46:34,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▌                                                                          | 149/2590 [01:15<46:04,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▌                                                                          | 150/2590 [01:16<45:51,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▌                                                                          | 151/2590 [01:16<39:24,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▋                                                                          | 152/2590 [01:17<39:22,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▋                                                                          | 153/2590 [01:18<33:05,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▋                                                                          | 154/2590 [01:18<28:59,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▋                                                                          | 155/2590 [01:19<26:40,  1.52it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▊                                                                          | 156/2590 [01:19<25:35,  1.59it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▊                                                                          | 157/2590 [01:20<24:45,  1.64it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▊                                                                          | 158/2590 [01:20<23:04,  1.76it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▊                                                                          | 159/2590 [01:21<22:37,  1.79it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▉                                                                          | 160/2590 [01:21<20:29,  1.98it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▉                                                                          | 161/2590 [01:22<20:15,  2.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▉                                                                          | 162/2590 [01:22<20:02,  2.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|████▉                                                                          | 163/2590 [01:23<21:11,  1.91it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|█████                                                                          | 164/2590 [01:23<19:42,  2.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|█████                                                                          | 165/2590 [01:24<17:10,  2.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|█████                                                                          | 166/2590 [01:24<15:00,  2.69it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  6%|█████                                                                          | 167/2590 [01:24<13:34,  2.97it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  6%|█████                                                                          | 168/2590 [01:25<15:24,  2.62it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▏                                                                         | 169/2590 [01:25<15:42,  2.57it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▏                                                                         | 170/2590 [01:25<16:28,  2.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▏                                                                         | 171/2590 [01:26<17:40,  2.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▏                                                                         | 172/2590 [01:27<23:30,  1.71it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▎                                                                         | 173/2590 [01:27<22:26,  1.80it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▎                                                                         | 174/2590 [01:28<25:37,  1.57it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▎                                                                         | 175/2590 [01:29<27:53,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▎                                                                         | 176/2590 [01:29<24:48,  1.62it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▍                                                                         | 177/2590 [01:30<26:19,  1.53it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▍                                                                         | 178/2590 [01:32<35:42,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▍                                                                         | 179/2590 [01:32<32:17,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▍                                                                         | 180/2590 [01:33<32:55,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▌                                                                         | 181/2590 [01:35<42:46,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▌                                                                         | 182/2590 [01:36<39:54,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▌                                                                         | 183/2590 [01:36<32:15,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▌                                                                         | 184/2590 [01:38<42:31,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                         | 185/2590 [01:40<52:38,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                         | 186/2590 [01:41<49:41,  1.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                         | 187/2590 [01:42<57:18,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                         | 188/2590 [01:44<58:41,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▌                                                                       | 189/2590 [01:48<1:31:32,  2.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                       | 190/2590 [01:50<1:27:22,  2.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                       | 191/2590 [01:53<1:33:45,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  7%|█████▋                                                                       | 192/2590 [01:54<1:20:48,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▋                                                                       | 193/2590 [01:56<1:16:27,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  7%|█████▊                                                                       | 194/2590 [01:59<1:26:31,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|█████▊                                                                       | 195/2590 [02:00<1:17:48,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|█████▊                                                                       | 196/2590 [02:02<1:16:24,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|█████▊                                                                       | 197/2590 [02:03<1:02:34,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                         | 198/2590 [02:04<57:21,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|█████▉                                                                       | 199/2590 [02:06<1:06:59,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                         | 200/2590 [02:07<55:11,  1.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|█████▉                                                                       | 201/2590 [02:10<1:19:00,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                       | 202/2590 [02:12<1:19:22,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                       | 203/2590 [02:14<1:20:13,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                       | 204/2590 [02:16<1:16:11,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                       | 205/2590 [02:17<1:08:33,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████                                                                       | 206/2590 [02:19<1:15:26,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▏                                                                      | 207/2590 [02:23<1:35:15,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▏                                                                      | 208/2590 [02:25<1:25:57,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▏                                                                      | 209/2590 [02:25<1:09:39,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▍                                                                        | 210/2590 [02:26<57:05,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▎                                                                      | 211/2590 [02:29<1:10:48,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▍                                                                        | 212/2590 [02:29<58:15,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▍                                                                        | 213/2590 [02:30<50:00,  1.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▌                                                                        | 214/2590 [02:31<47:13,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▌                                                                        | 215/2590 [02:32<41:40,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  8%|██████▌                                                                        | 216/2590 [02:33<38:54,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▌                                                                        | 217/2590 [02:34<41:34,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▋                                                                        | 218/2590 [02:36<48:41,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▋                                                                        | 219/2590 [02:38<56:35,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  8%|██████▌                                                                      | 220/2590 [02:41<1:16:16,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▌                                                                      | 221/2590 [02:43<1:20:00,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▌                                                                      | 222/2590 [02:45<1:15:53,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▋                                                                      | 223/2590 [02:45<1:00:38,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▊                                                                        | 224/2590 [02:46<50:47,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▊                                                                        | 225/2590 [02:47<42:59,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▉                                                                        | 226/2590 [02:47<38:50,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▉                                                                        | 227/2590 [02:48<35:05,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▉                                                                        | 228/2590 [02:49<34:53,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|██████▉                                                                        | 229/2590 [02:50<36:43,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████                                                                        | 230/2590 [02:51<33:31,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████                                                                        | 231/2590 [02:51<32:32,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████                                                                        | 232/2590 [02:52<30:51,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████                                                                        | 233/2590 [02:53<30:17,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▏                                                                       | 234/2590 [02:53<29:02,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▏                                                                       | 235/2590 [02:54<25:58,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▏                                                                       | 236/2590 [02:55<26:47,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▏                                                                       | 237/2590 [02:55<25:20,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▎                                                                       | 238/2590 [02:56<25:33,  1.53it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▎                                                                       | 239/2590 [02:56<25:12,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

  9%|███████▎                                                                       | 240/2590 [02:57<25:36,  1.53it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▎                                                                       | 241/2590 [02:58<25:22,  1.54it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▍                                                                       | 242/2590 [02:58<25:59,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▍                                                                       | 243/2590 [02:59<26:47,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▍                                                                       | 244/2590 [03:00<26:37,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▍                                                                       | 245/2590 [03:01<27:11,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
  9%|███████▌                                                                       | 246/2590 [03:01<26:23,  1.48it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▌                                                                       | 247/2590 [03:02<26:56,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▌                                                                       | 248/2590 [03:03<25:51,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▌                                                                       | 249/2590 [03:03<27:57,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▋                                                                       | 250/2590 [03:04<27:21,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▋                                                                       | 251/2590 [03:05<29:03,  1.34it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▋                                                                       | 252/2590 [03:05<26:31,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▋                                                                       | 253/2590 [03:06<25:25,  1.53it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▋                                                                       | 254/2590 [03:07<25:40,  1.52it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▊                                                                       | 255/2590 [03:07<25:11,  1.54it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▊                                                                       | 256/2590 [03:08<25:34,  1.52it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▊                                                                       | 257/2590 [03:09<26:23,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▊                                                                       | 258/2590 [03:09<24:40,  1.58it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▉                                                                       | 259/2590 [03:10<26:06,  1.49it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▉                                                                       | 260/2590 [03:11<25:40,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▉                                                                       | 261/2590 [03:11<26:24,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|███████▉                                                                       | 262/2590 [03:12<25:49,  1.50it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████                                                                       | 263/2590 [03:13<27:14,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 10%|████████                                                                       | 264/2590 [03:13<25:53,  1.50it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████                                                                       | 265/2590 [03:14<29:13,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████                                                                       | 266/2590 [03:15<27:50,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████▏                                                                      | 267/2590 [03:16<27:38,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████▏                                                                      | 268/2590 [03:16<27:56,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████▏                                                                      | 269/2590 [03:17<27:07,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████▏                                                                      | 270/2590 [03:18<28:10,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 10%|████████▎                                                                      | 271/2590 [03:18<25:50,  1.50it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▎                                                                      | 272/2590 [03:19<26:14,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▎                                                                      | 273/2590 [03:20<24:58,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▎                                                                      | 274/2590 [03:20<24:50,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▍                                                                      | 275/2590 [03:21<26:10,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▍                                                                      | 276/2590 [03:22<25:30,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▍                                                                      | 277/2590 [03:22<23:21,  1.65it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▍                                                                      | 278/2590 [03:23<23:20,  1.65it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▌                                                                      | 279/2590 [03:23<24:06,  1.60it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▌                                                                      | 280/2590 [03:24<25:33,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▌                                                                      | 281/2590 [03:25<25:09,  1.53it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▌                                                                      | 282/2590 [03:26<26:28,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▋                                                                      | 283/2590 [03:26<26:30,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▋                                                                      | 284/2590 [03:27<26:36,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▋                                                                      | 285/2590 [03:28<26:00,  1.48it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▋                                                                      | 286/2590 [03:28<26:42,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▊                                                                      | 287/2590 [03:29<24:36,  1.56it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 11%|████████▊                                                                      | 288/2590 [03:30<25:20,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▊                                                                      | 289/2590 [03:30<26:25,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▊                                                                      | 290/2590 [03:31<26:28,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▉                                                                      | 291/2590 [03:32<27:15,  1.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▉                                                                      | 292/2590 [03:32<26:16,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▉                                                                      | 293/2590 [03:33<25:37,  1.49it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▉                                                                      | 294/2590 [03:34<26:34,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|████████▉                                                                      | 295/2590 [03:34<25:27,  1.50it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|█████████                                                                      | 296/2590 [03:35<26:52,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 11%|█████████                                                                      | 297/2590 [03:36<26:04,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████                                                                      | 298/2590 [03:37<26:14,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████                                                                      | 299/2590 [03:37<27:18,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▏                                                                     | 300/2590 [03:38<26:46,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▏                                                                     | 301/2590 [03:39<27:55,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▏                                                                     | 302/2590 [03:39<26:39,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▏                                                                     | 303/2590 [03:41<31:07,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▎                                                                     | 304/2590 [03:41<31:25,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▎                                                                     | 305/2590 [03:42<30:45,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▎                                                                     | 306/2590 [03:43<31:31,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▎                                                                     | 307/2590 [03:44<31:52,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▍                                                                     | 308/2590 [03:45<31:11,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▍                                                                     | 309/2590 [03:45<31:08,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▍                                                                     | 310/2590 [03:46<28:04,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▍                                                                     | 311/2590 [03:47<27:02,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 12%|█████████▌                                                                     | 312/2590 [03:47<28:32,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▌                                                                     | 313/2590 [03:48<27:40,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▌                                                                     | 314/2590 [03:49<27:03,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▌                                                                     | 315/2590 [03:50<26:22,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▋                                                                     | 316/2590 [03:50<25:25,  1.49it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▋                                                                     | 317/2590 [03:51<24:58,  1.52it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▋                                                                     | 318/2590 [03:51<24:30,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▋                                                                     | 319/2590 [03:52<26:13,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▊                                                                     | 320/2590 [03:53<25:32,  1.48it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▊                                                                     | 321/2590 [03:53<23:26,  1.61it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▊                                                                     | 322/2590 [03:54<24:47,  1.52it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 12%|█████████▊                                                                     | 323/2590 [03:55<24:14,  1.56it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|█████████▉                                                                     | 324/2590 [03:55<25:25,  1.49it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|█████████▉                                                                     | 325/2590 [03:56<24:59,  1.51it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|█████████▉                                                                     | 326/2590 [03:57<24:24,  1.55it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|█████████▉                                                                     | 327/2590 [03:57<26:29,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████                                                                     | 328/2590 [03:58<25:59,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████                                                                     | 329/2590 [03:59<25:10,  1.50it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████                                                                     | 330/2590 [04:00<26:33,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████                                                                     | 331/2590 [04:00<25:37,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▏                                                                    | 332/2590 [04:01<25:19,  1.49it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▏                                                                    | 333/2590 [04:02<26:23,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▏                                                                    | 334/2590 [04:02<25:58,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▏                                                                    | 335/2590 [04:03<27:02,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 13%|██████████▏                                                                    | 336/2590 [04:04<26:47,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▎                                                                    | 337/2590 [04:04<25:35,  1.47it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▎                                                                    | 338/2590 [04:05<26:13,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▎                                                                    | 339/2590 [04:06<25:44,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▎                                                                    | 340/2590 [04:07<26:39,  1.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▍                                                                    | 341/2590 [04:07<26:04,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▍                                                                    | 342/2590 [04:08<26:09,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▍                                                                    | 343/2590 [04:09<26:46,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▍                                                                    | 344/2590 [04:09<25:47,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▌                                                                    | 345/2590 [04:10<26:46,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▌                                                                    | 346/2590 [04:11<27:02,  1.38it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▌                                                                    | 347/2590 [04:12<29:12,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▌                                                                    | 348/2590 [04:12<28:15,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 13%|██████████▋                                                                    | 349/2590 [04:13<28:34,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▋                                                                    | 350/2590 [04:14<28:39,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▋                                                                    | 351/2590 [04:15<27:33,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▋                                                                    | 352/2590 [04:15<28:34,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▊                                                                    | 353/2590 [04:16<27:06,  1.38it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▊                                                                    | 354/2590 [04:17<29:35,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▊                                                                    | 355/2590 [04:18<28:22,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▊                                                                    | 356/2590 [04:18<25:46,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▉                                                                    | 357/2590 [04:19<25:37,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▉                                                                    | 358/2590 [04:20<25:40,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|██████████▉                                                                    | 359/2590 [04:20<25:24,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 14%|██████████▉                                                                    | 360/2590 [04:21<26:37,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████                                                                    | 361/2590 [04:22<26:46,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████                                                                    | 362/2590 [04:23<29:41,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████                                                                    | 363/2590 [04:24<30:12,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████                                                                    | 364/2590 [04:25<31:26,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▏                                                                   | 365/2590 [04:25<30:29,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▏                                                                   | 366/2590 [04:26<29:58,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▏                                                                   | 367/2590 [04:27<31:01,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▏                                                                   | 368/2590 [04:28<30:17,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▎                                                                   | 369/2590 [04:29<29:13,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▎                                                                   | 370/2590 [04:29<29:33,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▎                                                                   | 371/2590 [04:30<28:01,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▎                                                                   | 372/2590 [04:31<28:10,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▍                                                                   | 373/2590 [04:32<28:58,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▍                                                                   | 374/2590 [04:32<28:18,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 14%|███████████▍                                                                   | 375/2590 [04:33<27:53,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▍                                                                   | 376/2590 [04:34<27:39,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▍                                                                   | 377/2590 [04:35<27:43,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▌                                                                   | 378/2590 [04:35<26:23,  1.40it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▌                                                                   | 379/2590 [04:36<25:38,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▌                                                                   | 380/2590 [04:37<27:00,  1.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▌                                                                   | 381/2590 [04:37<26:34,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▋                                                                   | 382/2590 [04:38<29:01,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▋                                                                   | 383/2590 [04:39<27:53,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 15%|███████████▋                                                                   | 384/2590 [04:40<26:50,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▋                                                                   | 385/2590 [04:40<27:28,  1.34it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▊                                                                   | 386/2590 [04:41<25:25,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▊                                                                   | 387/2590 [04:42<25:08,  1.46it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▊                                                                   | 388/2590 [04:42<25:34,  1.43it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▊                                                                   | 389/2590 [04:43<25:54,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▉                                                                   | 390/2590 [04:44<27:18,  1.34it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▉                                                                   | 391/2590 [04:45<27:11,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▉                                                                   | 392/2590 [04:46<28:29,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|███████████▉                                                                   | 393/2590 [04:47<30:45,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████                                                                   | 394/2590 [04:47<31:56,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████                                                                   | 395/2590 [04:49<34:49,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████                                                                   | 396/2590 [04:49<33:58,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████                                                                   | 397/2590 [04:51<35:08,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████▏                                                                  | 398/2590 [04:51<31:18,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████▏                                                                  | 399/2590 [04:52<30:44,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████▏                                                                  | 400/2590 [04:53<28:31,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 15%|████████████▏                                                                  | 401/2590 [04:53<28:34,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▎                                                                  | 402/2590 [04:54<23:00,  1.58it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▎                                                                  | 403/2590 [04:55<26:10,  1.39it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▎                                                                  | 404/2590 [04:55<26:51,  1.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▎                                                                  | 405/2590 [04:56<27:35,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▍                                                                  | 406/2590 [04:57<27:00,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▍                                                                  | 407/2590 [04:58<27:55,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 16%|████████████▍                                                                  | 408/2590 [04:58<27:50,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▍                                                                  | 409/2590 [04:59<26:47,  1.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▌                                                                  | 410/2590 [05:00<27:13,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▌                                                                  | 411/2590 [05:01<27:03,  1.34it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▌                                                                  | 412/2590 [05:01<25:41,  1.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▌                                                                  | 413/2590 [05:02<24:29,  1.48it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▋                                                                  | 414/2590 [05:03<25:06,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▋                                                                  | 415/2590 [05:03<26:15,  1.38it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▋                                                                  | 416/2590 [05:04<25:03,  1.45it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▋                                                                  | 417/2590 [05:05<25:30,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▋                                                                  | 418/2590 [05:06<27:12,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▊                                                                  | 419/2590 [05:06<26:29,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▊                                                                  | 420/2590 [05:07<27:55,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▊                                                                  | 421/2590 [05:08<27:17,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▊                                                                  | 422/2590 [05:09<26:43,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▉                                                                  | 423/2590 [05:09<28:15,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▉                                                                  | 424/2590 [05:10<27:04,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▉                                                                  | 425/2590 [05:11<27:18,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|████████████▉                                                                  | 426/2590 [05:12<28:00,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 16%|█████████████                                                                  | 427/2590 [05:12<27:35,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████                                                                  | 428/2590 [05:13<28:39,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████                                                                  | 429/2590 [05:14<28:56,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████                                                                  | 430/2590 [05:15<28:20,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▏                                                                 | 431/2590 [05:16<29:24,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 17%|█████████████▏                                                                 | 432/2590 [05:16<28:08,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▏                                                                 | 433/2590 [05:17<29:08,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▏                                                                 | 434/2590 [05:18<28:31,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▎                                                                 | 435/2590 [05:19<27:06,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▎                                                                 | 436/2590 [05:20<28:24,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▎                                                                 | 437/2590 [05:20<27:47,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▎                                                                 | 438/2590 [05:21<27:40,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▍                                                                 | 439/2590 [05:22<28:37,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▍                                                                 | 440/2590 [05:23<28:02,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▍                                                                 | 441/2590 [05:24<29:20,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▍                                                                 | 442/2590 [05:24<27:58,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▌                                                                 | 443/2590 [05:25<27:37,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▌                                                                 | 444/2590 [05:26<28:01,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▌                                                                 | 445/2590 [05:27<28:50,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▌                                                                 | 446/2590 [05:28<28:26,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▋                                                                 | 447/2590 [05:28<29:26,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▋                                                                 | 448/2590 [05:29<28:33,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▋                                                                 | 449/2590 [05:30<30:29,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▋                                                                 | 450/2590 [05:31<30:31,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▊                                                                 | 451/2590 [05:32<31:22,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▊                                                                 | 452/2590 [05:33<29:14,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 17%|█████████████▊                                                                 | 453/2590 [05:33<27:19,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|█████████████▊                                                                 | 454/2590 [05:34<28:39,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|█████████████▉                                                                 | 455/2590 [05:35<27:33,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 18%|█████████████▉                                                                 | 456/2590 [05:36<29:15,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|█████████████▉                                                                 | 457/2590 [05:36<26:40,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|█████████████▉                                                                 | 458/2590 [05:37<26:50,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████                                                                 | 459/2590 [05:38<24:38,  1.44it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████                                                                 | 460/2590 [05:39<26:13,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████                                                                 | 461/2590 [05:39<26:01,  1.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████                                                                 | 462/2590 [05:40<28:31,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████                                                                 | 463/2590 [05:41<27:36,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▏                                                                | 464/2590 [05:42<26:36,  1.33it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▏                                                                | 465/2590 [05:43<27:41,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▏                                                                | 466/2590 [05:43<26:48,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▏                                                                | 467/2590 [05:44<28:09,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▎                                                                | 468/2590 [05:45<27:49,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▎                                                                | 469/2590 [05:46<27:36,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▎                                                                | 470/2590 [05:46<27:51,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▎                                                                | 471/2590 [05:47<27:57,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▍                                                                | 472/2590 [05:48<26:47,  1.32it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▍                                                                | 473/2590 [05:49<28:14,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▍                                                                | 474/2590 [05:50<27:55,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▍                                                                | 475/2590 [05:50<23:44,  1.48it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▌                                                                | 476/2590 [05:51<26:47,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▌                                                                | 477/2590 [05:51<22:24,  1.57it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▌                                                                | 478/2590 [05:52<19:32,  1.80it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 18%|██████████████▌                                                                | 479/2590 [05:53<24:42,  1.42it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 19%|██████████████▋                                                                | 480/2590 [05:54<29:08,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▋                                                                | 481/2590 [05:55<29:35,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▋                                                                | 482/2590 [05:56<30:45,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▋                                                                | 483/2590 [05:57<33:50,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▊                                                                | 484/2590 [05:58<32:09,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▊                                                                | 485/2590 [05:59<32:12,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▊                                                                | 486/2590 [05:59<30:36,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▊                                                                | 487/2590 [06:00<28:51,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▉                                                                | 488/2590 [06:01<29:11,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▉                                                                | 489/2590 [06:02<28:27,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▉                                                                | 490/2590 [06:03<29:04,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|██████████████▉                                                                | 491/2590 [06:03<28:39,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████                                                                | 492/2590 [06:04<28:10,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████                                                                | 493/2590 [06:05<27:41,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████                                                                | 494/2590 [06:05<25:22,  1.38it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████                                                                | 495/2590 [06:06<25:40,  1.36it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▏                                                               | 496/2590 [06:07<27:40,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▏                                                               | 497/2590 [06:08<26:51,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▏                                                               | 498/2590 [06:09<28:38,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▏                                                               | 499/2590 [06:09<25:23,  1.37it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▎                                                               | 500/2590 [06:10<25:48,  1.35it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▎                                                               | 501/2590 [06:11<27:58,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▎                                                               | 502/2590 [06:12<28:07,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▎                                                               | 503/2590 [06:13<29:30,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 19%|███████████████▎                                                               | 504/2590 [06:14<29:54,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 19%|███████████████▍                                                               | 505/2590 [06:14<29:21,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▍                                                               | 506/2590 [06:15<29:41,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▍                                                               | 507/2590 [06:16<27:49,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▍                                                               | 508/2590 [06:17<27:39,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▌                                                               | 509/2590 [06:18<29:18,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▌                                                               | 510/2590 [06:19<28:20,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▌                                                               | 511/2590 [06:19<27:56,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▌                                                               | 512/2590 [06:20<29:01,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▋                                                               | 513/2590 [06:21<28:38,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▋                                                               | 514/2590 [06:22<29:00,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▋                                                               | 515/2590 [06:23<28:54,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▋                                                               | 516/2590 [06:23<27:17,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▊                                                               | 517/2590 [06:24<29:07,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▊                                                               | 518/2590 [06:25<27:37,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▊                                                               | 519/2590 [06:26<27:21,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▊                                                               | 520/2590 [06:27<28:31,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▉                                                               | 521/2590 [06:28<28:11,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▉                                                               | 522/2590 [06:28<27:37,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▉                                                               | 523/2590 [06:29<30:11,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|███████████████▉                                                               | 524/2590 [06:30<29:30,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|████████████████                                                               | 525/2590 [06:31<31:10,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|████████████████                                                               | 526/2590 [06:32<30:45,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|████████████████                                                               | 527/2590 [06:33<30:19,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 20%|████████████████                                                               | 528/2590 [06:34<31:01,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|████████████████▏                                                              | 529/2590 [06:35<30:19,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 20%|████████████████▏                                                              | 530/2590 [06:36<30:47,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▏                                                              | 531/2590 [06:36<30:08,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▏                                                              | 532/2590 [06:37<29:29,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▎                                                              | 533/2590 [06:38<31:10,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▎                                                              | 534/2590 [06:39<30:16,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▎                                                              | 535/2590 [06:40<29:57,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▎                                                              | 536/2590 [06:41<28:45,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▍                                                              | 537/2590 [06:41<27:50,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▍                                                              | 538/2590 [06:42<28:35,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▍                                                              | 539/2590 [06:43<28:28,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▍                                                              | 540/2590 [06:44<30:24,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▌                                                              | 541/2590 [06:45<31:53,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▌                                                              | 542/2590 [06:46<30:29,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▌                                                              | 543/2590 [06:47<29:25,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▌                                                              | 544/2590 [06:48<29:19,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▌                                                              | 545/2590 [06:49<29:46,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▋                                                              | 546/2590 [06:50<30:02,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▋                                                              | 547/2590 [06:50<28:48,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▋                                                              | 548/2590 [06:51<30:13,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▋                                                              | 549/2590 [06:52<30:04,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▊                                                              | 550/2590 [06:53<28:54,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▊                                                              | 551/2590 [06:54<30:12,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 21%|████████████████▊                                                              | 552/2590 [06:55<29:24,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▊                                                              | 553/2590 [06:55<28:45,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▉                                                              | 554/2590 [06:56<29:25,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▉                                                              | 555/2590 [06:57<25:51,  1.31it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 21%|████████████████▉                                                              | 556/2590 [06:58<27:28,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|████████████████▉                                                              | 557/2590 [06:59<29:49,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████                                                              | 558/2590 [07:00<31:18,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████                                                              | 559/2590 [07:01<32:33,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████                                                              | 560/2590 [07:02<33:44,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████                                                              | 561/2590 [07:03<31:40,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▏                                                             | 562/2590 [07:04<29:21,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▏                                                             | 563/2590 [07:05<30:27,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▏                                                             | 564/2590 [07:05<28:55,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▏                                                             | 565/2590 [07:06<28:45,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▎                                                             | 566/2590 [07:07<29:30,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▎                                                             | 567/2590 [07:08<27:29,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▎                                                             | 568/2590 [07:08<26:18,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▎                                                             | 569/2590 [07:09<28:02,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▍                                                             | 570/2590 [07:10<26:28,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▍                                                             | 571/2590 [07:11<26:35,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▍                                                             | 572/2590 [07:12<28:08,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▍                                                             | 573/2590 [07:12<25:55,  1.30it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▌                                                             | 574/2590 [07:13<26:03,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▌                                                             | 575/2590 [07:14<26:19,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 22%|█████████████████▌                                                             | 576/2590 [07:15<26:39,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▌                                                             | 577/2590 [07:16<26:02,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▋                                                             | 578/2590 [07:16<26:21,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▋                                                             | 579/2590 [07:17<27:58,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▋                                                             | 580/2590 [07:18<26:38,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▋                                                             | 581/2590 [07:19<26:12,  1.28it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 22%|█████████████████▊                                                             | 582/2590 [07:20<26:22,  1.27it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▊                                                             | 583/2590 [07:21<27:48,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▊                                                             | 584/2590 [07:21<26:59,  1.24it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▊                                                             | 585/2590 [07:22<26:40,  1.25it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▊                                                             | 586/2590 [07:23<28:02,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▉                                                             | 587/2590 [07:24<27:17,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▉                                                             | 588/2590 [07:25<29:18,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▉                                                             | 589/2590 [07:26<27:56,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|█████████████████▉                                                             | 590/2590 [07:27<29:40,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████                                                             | 591/2590 [07:27<29:02,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████                                                             | 592/2590 [07:28<29:05,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████                                                             | 593/2590 [07:29<30:09,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████                                                             | 594/2590 [07:30<29:18,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▏                                                            | 595/2590 [07:31<31:03,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▏                                                            | 596/2590 [07:32<31:27,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▏                                                            | 597/2590 [07:33<31:33,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▏                                                            | 598/2590 [07:34<31:37,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▎                                                            | 599/2590 [07:35<31:03,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 23%|██████████████████▎                                                            | 600/2590 [07:36<32:04,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▎                                                            | 601/2590 [07:37<30:30,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▎                                                            | 602/2590 [07:38<29:53,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▍                                                            | 603/2590 [07:39<31:47,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▍                                                            | 604/2590 [07:40<30:51,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▍                                                            | 605/2590 [07:40<29:46,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▍                                                            | 606/2590 [07:41<30:34,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▌                                                            | 607/2590 [07:42<31:20,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 23%|██████████████████▌                                                            | 608/2590 [07:43<31:01,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▌                                                            | 609/2590 [07:44<29:06,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▌                                                            | 610/2590 [07:45<28:55,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▋                                                            | 611/2590 [07:46<30:01,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▋                                                            | 612/2590 [07:47<28:53,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▋                                                            | 613/2590 [07:48<28:38,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▋                                                            | 614/2590 [07:48<29:29,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▊                                                            | 615/2590 [07:49<29:06,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▊                                                            | 616/2590 [07:50<28:38,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▊                                                            | 617/2590 [07:51<30:16,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▊                                                            | 618/2590 [07:52<29:19,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▉                                                            | 619/2590 [07:53<29:24,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▉                                                            | 620/2590 [07:54<29:58,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▉                                                            | 621/2590 [07:55<28:18,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|██████████████████▉                                                            | 622/2590 [07:55<27:19,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████                                                            | 623/2590 [07:56<27:15,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 24%|███████████████████                                                            | 624/2590 [07:57<28:20,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████                                                            | 625/2590 [07:58<27:51,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████                                                            | 626/2590 [07:58<23:14,  1.41it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████                                                            | 627/2590 [07:59<26:35,  1.23it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▏                                                           | 628/2590 [08:00<25:58,  1.26it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▏                                                           | 629/2590 [08:01<25:19,  1.29it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▏                                                           | 630/2590 [08:02<27:36,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▏                                                           | 631/2590 [08:03<27:09,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▎                                                           | 632/2590 [08:04<29:52,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▎                                                           | 633/2590 [08:05<28:08,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 24%|███████████████████▎                                                           | 634/2590 [08:06<28:44,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▎                                                           | 635/2590 [08:07<32:54,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▍                                                           | 636/2590 [08:08<33:38,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▍                                                           | 637/2590 [08:09<33:32,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▍                                                           | 638/2590 [08:10<32:22,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▍                                                           | 639/2590 [08:11<30:12,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▌                                                           | 640/2590 [08:11<29:21,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▌                                                           | 641/2590 [08:12<30:16,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▌                                                           | 642/2590 [08:13<28:12,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▌                                                           | 643/2590 [08:14<28:26,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▋                                                           | 644/2590 [08:15<29:32,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▋                                                           | 645/2590 [08:16<28:46,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▋                                                           | 646/2590 [08:17<30:01,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▋                                                           | 647/2590 [08:18<29:03,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 25%|███████████████████▊                                                           | 648/2590 [08:19<28:23,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▊                                                           | 649/2590 [08:20<30:28,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▊                                                           | 650/2590 [08:21<29:30,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▊                                                           | 651/2590 [08:22<30:19,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▉                                                           | 652/2590 [08:22<29:20,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▉                                                           | 653/2590 [08:23<29:47,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▉                                                           | 654/2590 [08:24<29:01,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|███████████████████▉                                                           | 655/2590 [08:25<28:21,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|████████████████████                                                           | 656/2590 [08:26<28:00,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|████████████████████                                                           | 657/2590 [08:27<28:55,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|████████████████████                                                           | 658/2590 [08:28<28:54,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|████████████████████                                                           | 659/2590 [08:29<30:10,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 25%|████████████████████▏                                                          | 660/2590 [08:30<29:51,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▏                                                          | 661/2590 [08:30<29:15,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▏                                                          | 662/2590 [08:31<29:53,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▏                                                          | 663/2590 [08:32<28:28,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▎                                                          | 664/2590 [08:33<27:34,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▎                                                          | 665/2590 [08:34<27:15,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▎                                                          | 666/2590 [08:35<27:23,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▎                                                          | 667/2590 [08:36<27:50,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▍                                                          | 668/2590 [08:37<28:47,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▍                                                          | 669/2590 [08:37<27:36,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▍                                                          | 670/2590 [08:38<26:12,  1.22it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▍                                                          | 671/2590 [08:39<28:19,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 26%|████████████████████▍                                                          | 672/2590 [08:40<26:43,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▌                                                          | 673/2590 [08:41<26:50,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▌                                                          | 674/2590 [08:42<28:20,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▌                                                          | 675/2590 [08:43<28:01,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▌                                                          | 676/2590 [08:43<28:18,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▋                                                          | 677/2590 [08:44<28:42,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▋                                                          | 678/2590 [08:45<27:43,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▋                                                          | 679/2590 [08:46<26:58,  1.18it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▋                                                          | 680/2590 [08:47<26:31,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▊                                                          | 681/2590 [08:48<26:27,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▊                                                          | 682/2590 [08:49<28:33,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▊                                                          | 683/2590 [08:49<27:14,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▊                                                          | 684/2590 [08:50<27:18,  1.16it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▉                                                          | 685/2590 [08:51<28:57,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 26%|████████████████████▉                                                          | 686/2590 [08:52<29:02,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|████████████████████▉                                                          | 687/2590 [08:53<27:39,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|████████████████████▉                                                          | 688/2590 [08:54<28:47,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████                                                          | 689/2590 [08:55<28:13,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████                                                          | 690/2590 [08:56<27:51,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████                                                          | 691/2590 [08:57<28:35,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████                                                          | 692/2590 [08:58<27:53,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▏                                                         | 693/2590 [08:58<26:11,  1.21it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▏                                                         | 694/2590 [08:59<27:30,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▏                                                         | 695/2590 [09:00<27:28,  1.15it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 27%|█████████████████████▏                                                         | 696/2590 [09:01<28:38,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▎                                                         | 697/2590 [09:02<26:31,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▎                                                         | 698/2590 [09:03<26:52,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▎                                                         | 699/2590 [09:04<28:40,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▎                                                         | 700/2590 [09:05<28:36,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▍                                                         | 701/2590 [09:05<28:23,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▍                                                         | 702/2590 [09:07<30:22,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▍                                                         | 703/2590 [09:07<29:18,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▍                                                         | 704/2590 [09:08<30:20,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▌                                                         | 705/2590 [09:09<29:42,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▌                                                         | 706/2590 [09:10<30:21,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▌                                                         | 707/2590 [09:12<32:23,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▌                                                         | 708/2590 [09:13<33:43,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▋                                                         | 709/2590 [09:14<31:54,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▋                                                         | 710/2590 [09:15<33:18,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▋                                                         | 711/2590 [09:16<31:18,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 27%|█████████████████████▋                                                         | 712/2590 [09:17<32:25,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▋                                                         | 713/2590 [09:19<42:32,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▊                                                         | 714/2590 [09:22<55:08,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▊                                                         | 715/2590 [09:23<50:34,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▊                                                         | 716/2590 [09:24<44:20,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▊                                                         | 717/2590 [09:25<39:46,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▉                                                         | 718/2590 [09:26<37:48,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▉                                                         | 719/2590 [09:27<38:22,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 28%|█████████████████████▉                                                         | 720/2590 [09:28<34:24,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|█████████████████████▉                                                         | 721/2590 [09:29<31:12,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████                                                         | 722/2590 [09:30<31:54,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████                                                         | 723/2590 [09:30<28:53,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████                                                         | 724/2590 [09:31<28:45,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████                                                         | 725/2590 [09:32<29:25,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▏                                                        | 726/2590 [09:33<28:09,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▏                                                        | 727/2590 [09:34<28:17,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▏                                                        | 728/2590 [09:36<36:52,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▏                                                        | 729/2590 [09:37<39:46,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▎                                                        | 730/2590 [09:39<38:48,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▎                                                        | 731/2590 [09:40<40:27,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▎                                                        | 732/2590 [09:42<45:40,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▎                                                        | 733/2590 [09:43<42:09,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▍                                                        | 734/2590 [09:44<39:24,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▍                                                        | 735/2590 [09:45<36:09,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▍                                                        | 736/2590 [09:46<33:27,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▍                                                        | 737/2590 [09:47<33:32,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 28%|██████████████████████▌                                                        | 738/2590 [09:48<32:13,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▌                                                        | 739/2590 [09:49<30:03,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▌                                                        | 740/2590 [09:50<30:47,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▌                                                        | 741/2590 [09:51<29:05,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▋                                                        | 742/2590 [09:51<27:30,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▋                                                        | 743/2590 [09:53<29:43,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 29%|██████████████████████▋                                                        | 744/2590 [09:53<29:38,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▋                                                        | 745/2590 [09:54<25:43,  1.20it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▊                                                        | 746/2590 [09:55<27:37,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▊                                                        | 747/2590 [09:56<27:00,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▊                                                        | 748/2590 [09:57<26:59,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▊                                                        | 749/2590 [09:58<27:25,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▉                                                        | 750/2590 [09:59<29:50,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▉                                                        | 751/2590 [10:00<28:41,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▉                                                        | 752/2590 [10:01<27:41,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▉                                                        | 753/2590 [10:02<28:07,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|██████████████████████▉                                                        | 754/2590 [10:02<27:46,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████                                                        | 755/2590 [10:03<27:07,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████                                                        | 756/2590 [10:04<29:15,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████                                                        | 757/2590 [10:05<28:08,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████                                                        | 758/2590 [10:06<27:44,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▏                                                       | 759/2590 [10:07<28:52,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▏                                                       | 760/2590 [10:08<28:38,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▏                                                       | 761/2590 [10:09<28:25,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▏                                                       | 762/2590 [10:10<27:52,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▎                                                       | 763/2590 [10:11<29:52,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 29%|███████████████████████▎                                                       | 764/2590 [10:12<28:40,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▎                                                       | 765/2590 [10:13<27:48,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▎                                                       | 766/2590 [10:14<29:12,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▍                                                       | 767/2590 [10:15<28:46,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 30%|███████████████████████▍                                                       | 768/2590 [10:15<27:54,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▍                                                       | 769/2590 [10:17<29:30,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▍                                                       | 770/2590 [10:18<29:23,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▌                                                       | 771/2590 [10:19<30:00,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▌                                                       | 772/2590 [10:20<33:44,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▌                                                       | 773/2590 [10:21<34:29,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▌                                                       | 774/2590 [10:22<34:14,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▋                                                       | 775/2590 [10:23<34:10,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▋                                                       | 776/2590 [10:24<30:47,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▋                                                       | 777/2590 [10:25<29:54,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▋                                                       | 778/2590 [10:26<27:42,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▊                                                       | 779/2590 [10:27<26:56,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▊                                                       | 780/2590 [10:28<26:34,  1.14it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▊                                                       | 781/2590 [10:28<26:59,  1.12it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▊                                                       | 782/2590 [10:30<28:46,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▉                                                       | 783/2590 [10:30<27:57,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▉                                                       | 784/2590 [10:31<27:35,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▉                                                       | 785/2590 [10:32<28:04,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|███████████████████████▉                                                       | 786/2590 [10:33<27:29,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|████████████████████████                                                       | 787/2590 [10:34<27:19,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|████████████████████████                                                       | 788/2590 [10:35<29:09,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 30%|████████████████████████                                                       | 789/2590 [10:36<28:04,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████                                                       | 790/2590 [10:37<26:54,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▏                                                      | 791/2590 [10:38<26:36,  1.13it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 31%|████████████████████████▏                                                      | 792/2590 [10:39<29:34,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▏                                                      | 793/2590 [10:40<28:32,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▏                                                      | 794/2590 [10:41<26:53,  1.11it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▏                                                      | 795/2590 [10:42<30:45,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▎                                                      | 796/2590 [10:43<30:23,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▎                                                      | 797/2590 [10:44<28:22,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▎                                                      | 798/2590 [10:45<29:42,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▎                                                      | 799/2590 [10:46<29:03,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▍                                                      | 800/2590 [10:47<27:59,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▍                                                      | 801/2590 [10:47<27:32,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▍                                                      | 802/2590 [10:49<30:01,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▍                                                      | 803/2590 [10:50<29:09,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▌                                                      | 804/2590 [10:51<31:27,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▌                                                      | 805/2590 [10:52<29:55,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▌                                                      | 806/2590 [10:53<28:43,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▌                                                      | 807/2590 [10:54<29:50,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▋                                                      | 808/2590 [10:54<27:57,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▋                                                      | 809/2590 [10:55<27:39,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▋                                                      | 810/2590 [10:56<27:59,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▋                                                      | 811/2590 [10:58<30:29,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▊                                                      | 812/2590 [10:59<29:50,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▊                                                      | 813/2590 [10:59<29:18,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▊                                                      | 814/2590 [11:01<30:50,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 31%|████████████████████████▊                                                      | 815/2590 [11:02<30:38,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 32%|████████████████████████▉                                                      | 816/2590 [11:03<29:49,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|████████████████████████▉                                                      | 817/2590 [11:04<31:12,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|████████████████████████▉                                                      | 818/2590 [11:05<29:50,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|████████████████████████▉                                                      | 819/2590 [11:06<30:13,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████                                                      | 820/2590 [11:07<28:47,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████                                                      | 821/2590 [11:07<28:10,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████                                                      | 822/2590 [11:08<27:36,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████                                                      | 823/2590 [11:09<27:56,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▏                                                     | 824/2590 [11:10<28:09,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▏                                                     | 825/2590 [11:11<27:38,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▏                                                     | 826/2590 [11:12<30:04,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▏                                                     | 827/2590 [11:13<28:37,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▎                                                     | 828/2590 [11:14<30:03,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▎                                                     | 829/2590 [11:16<30:18,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▎                                                     | 830/2590 [11:17<30:19,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▎                                                     | 831/2590 [11:18<33:02,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▍                                                     | 832/2590 [11:19<31:30,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▍                                                     | 833/2590 [11:20<29:56,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▍                                                     | 834/2590 [11:21<31:50,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▍                                                     | 835/2590 [11:22<30:39,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▍                                                     | 836/2590 [11:23<30:02,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▌                                                     | 837/2590 [11:24<32:36,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▌                                                     | 838/2590 [11:25<31:56,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▌                                                     | 839/2590 [11:27<33:33,  1.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 32%|█████████████████████████▌                                                     | 840/2590 [11:28<35:14,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 32%|█████████████████████████▋                                                     | 841/2590 [11:29<32:20,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▋                                                     | 842/2590 [11:30<30:18,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▋                                                     | 843/2590 [11:31<30:09,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▋                                                     | 844/2590 [11:32<31:26,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▊                                                     | 845/2590 [11:33<30:07,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▊                                                     | 846/2590 [11:34<29:20,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▊                                                     | 847/2590 [11:35<29:48,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▊                                                     | 848/2590 [11:36<28:55,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▉                                                     | 849/2590 [11:37<30:11,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▉                                                     | 850/2590 [11:38<33:29,  1.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▉                                                     | 851/2590 [11:40<35:09,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|█████████████████████████▉                                                     | 852/2590 [11:41<38:21,  1.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████                                                     | 853/2590 [11:43<43:59,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████                                                     | 854/2590 [11:45<46:05,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████                                                     | 855/2590 [11:46<40:39,  1.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████                                                     | 856/2590 [11:47<41:20,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▏                                                    | 857/2590 [11:49<38:40,  1.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▏                                                    | 858/2590 [11:50<35:29,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▏                                                    | 859/2590 [11:51<34:28,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▏                                                    | 860/2590 [11:52<31:43,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▎                                                    | 861/2590 [11:52<30:21,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▎                                                    | 862/2590 [11:53<26:20,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▎                                                    | 863/2590 [11:54<28:14,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 33%|██████████████████████████▎                                                    | 864/2590 [11:55<27:39,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▍                                                    | 865/2590 [11:56<26:57,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▍                                                    | 866/2590 [11:57<26:32,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 33%|██████████████████████████▍                                                    | 867/2590 [11:58<28:24,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▍                                                    | 868/2590 [11:59<28:03,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▌                                                    | 869/2590 [12:00<27:21,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▌                                                    | 870/2590 [12:01<26:45,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▌                                                    | 871/2590 [12:02<28:31,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▌                                                    | 872/2590 [12:03<29:29,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▋                                                    | 873/2590 [12:04<28:44,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▋                                                    | 874/2590 [12:05<30:33,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▋                                                    | 875/2590 [12:06<29:22,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▋                                                    | 876/2590 [12:07<30:47,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▊                                                    | 877/2590 [12:08<29:25,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▊                                                    | 878/2590 [12:09<28:54,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▊                                                    | 879/2590 [12:10<30:56,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▊                                                    | 880/2590 [12:11<29:16,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▊                                                    | 881/2590 [12:12<28:52,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▉                                                    | 882/2590 [12:13<27:40,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▉                                                    | 883/2590 [12:15<31:03,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▉                                                    | 884/2590 [12:16<30:01,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|██████████████████████████▉                                                    | 885/2590 [12:17<29:05,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████                                                    | 886/2590 [12:18<29:26,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████                                                    | 887/2590 [12:18<27:53,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 34%|███████████████████████████                                                    | 888/2590 [12:19<27:38,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████                                                    | 889/2590 [12:20<27:43,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████▏                                                   | 890/2590 [12:22<29:04,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████▏                                                   | 891/2590 [12:22<27:20,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████▏                                                   | 892/2590 [12:23<26:17,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 34%|███████████████████████████▏                                                   | 893/2590 [12:24<28:33,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▎                                                   | 894/2590 [12:25<28:45,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▎                                                   | 895/2590 [12:26<27:43,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▎                                                   | 896/2590 [12:27<27:55,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▎                                                   | 897/2590 [12:28<27:23,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▍                                                   | 898/2590 [12:29<28:01,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▍                                                   | 899/2590 [12:30<29:45,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▍                                                   | 900/2590 [12:32<30:28,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▍                                                   | 901/2590 [12:33<34:53,  1.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▌                                                   | 902/2590 [12:34<33:47,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▌                                                   | 903/2590 [12:36<34:30,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▌                                                   | 904/2590 [12:37<33:26,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▌                                                   | 905/2590 [12:38<32:38,  1.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▋                                                   | 906/2590 [12:39<30:56,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▋                                                   | 907/2590 [12:40<29:19,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▋                                                   | 908/2590 [12:41<30:38,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▋                                                   | 909/2590 [12:42<28:58,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▊                                                   | 910/2590 [12:43<27:53,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▊                                                   | 911/2590 [12:44<28:51,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 35%|███████████████████████████▊                                                   | 912/2590 [12:45<28:32,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▊                                                   | 913/2590 [12:46<27:04,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▉                                                   | 914/2590 [12:47<28:25,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▉                                                   | 915/2590 [12:48<27:36,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▉                                                   | 916/2590 [12:49<29:32,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|███████████████████████████▉                                                   | 917/2590 [12:50<30:53,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|████████████████████████████                                                   | 918/2590 [12:51<32:30,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 35%|████████████████████████████                                                   | 919/2590 [12:52<30:24,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████                                                   | 920/2590 [12:54<31:38,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████                                                   | 921/2590 [12:55<30:11,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████                                                   | 922/2590 [12:56<30:25,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▏                                                  | 923/2590 [12:57<31:41,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▏                                                  | 924/2590 [12:58<30:18,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▏                                                  | 925/2590 [12:59<28:57,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▏                                                  | 926/2590 [13:00<28:47,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▎                                                  | 927/2590 [13:01<27:26,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▎                                                  | 928/2590 [13:02<27:14,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▎                                                  | 929/2590 [13:03<25:22,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▎                                                  | 930/2590 [13:04<27:18,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▍                                                  | 931/2590 [13:05<26:58,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▍                                                  | 932/2590 [13:06<26:49,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▍                                                  | 933/2590 [13:07<26:46,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▍                                                  | 934/2590 [13:08<29:20,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▌                                                  | 935/2590 [13:09<26:21,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 36%|████████████████████████████▌                                                  | 936/2590 [13:09<26:06,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▌                                                  | 937/2590 [13:11<27:52,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▌                                                  | 938/2590 [13:12<27:51,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▋                                                  | 939/2590 [13:12<26:07,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▋                                                  | 940/2590 [13:14<28:41,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▋                                                  | 941/2590 [13:15<28:23,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▋                                                  | 942/2590 [13:16<28:37,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▊                                                  | 943/2590 [13:17<31:19,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▊                                                  | 944/2590 [13:18<28:58,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 36%|████████████████████████████▊                                                  | 945/2590 [13:19<28:19,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|████████████████████████████▊                                                  | 946/2590 [13:20<28:54,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|████████████████████████████▉                                                  | 947/2590 [13:21<28:00,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|████████████████████████████▉                                                  | 948/2590 [13:22<27:42,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|████████████████████████████▉                                                  | 949/2590 [13:23<30:02,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|████████████████████████████▉                                                  | 950/2590 [13:24<28:17,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████                                                  | 951/2590 [13:25<26:35,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████                                                  | 952/2590 [13:26<25:31,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████                                                  | 953/2590 [13:27<27:43,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████                                                  | 954/2590 [13:28<27:16,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▏                                                 | 955/2590 [13:29<26:39,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▏                                                 | 956/2590 [13:30<26:03,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▏                                                 | 957/2590 [13:31<27:43,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▏                                                 | 958/2590 [13:32<27:25,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▎                                                 | 959/2590 [13:33<26:57,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 37%|█████████████████████████████▎                                                 | 960/2590 [13:34<28:48,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▎                                                 | 961/2590 [13:35<27:34,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▎                                                 | 962/2590 [13:36<26:18,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▎                                                 | 963/2590 [13:37<25:54,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▍                                                 | 964/2590 [13:38<27:43,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▍                                                 | 965/2590 [13:39<25:25,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▍                                                 | 966/2590 [13:40<25:43,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▍                                                 | 967/2590 [13:41<29:30,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▌                                                 | 968/2590 [13:42<28:24,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▌                                                 | 969/2590 [13:43<30:32,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▌                                                 | 970/2590 [13:45<30:39,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 37%|█████████████████████████████▌                                                 | 971/2590 [13:46<32:12,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▋                                                 | 972/2590 [13:47<30:10,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▋                                                 | 973/2590 [13:48<27:49,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▋                                                 | 974/2590 [13:49<29:06,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▋                                                 | 975/2590 [13:50<28:11,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▊                                                 | 976/2590 [13:51<27:09,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▊                                                 | 977/2590 [13:52<25:19,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▊                                                 | 978/2590 [13:53<27:33,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▊                                                 | 979/2590 [13:54<26:35,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▉                                                 | 980/2590 [13:55<26:04,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▉                                                 | 981/2590 [13:56<25:15,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▉                                                 | 982/2590 [13:57<27:04,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|█████████████████████████████▉                                                 | 983/2590 [13:58<26:20,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 38%|██████████████████████████████                                                 | 984/2590 [13:59<26:30,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████                                                 | 985/2590 [14:00<29:39,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████                                                 | 986/2590 [14:01<28:03,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████                                                 | 987/2590 [14:02<27:26,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▏                                                | 988/2590 [14:03<27:07,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▏                                                | 989/2590 [14:04<29:04,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▏                                                | 990/2590 [14:05<28:51,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▏                                                | 991/2590 [14:06<27:56,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▎                                                | 992/2590 [14:07<28:50,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▎                                                | 993/2590 [14:08<28:23,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▎                                                | 994/2590 [14:09<27:38,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▎                                                | 995/2590 [14:11<29:15,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▍                                                | 996/2590 [14:12<28:21,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 38%|██████████████████████████████▍                                                | 997/2590 [14:13<27:13,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                                | 998/2590 [14:14<29:25,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                                | 999/2590 [14:15<27:19,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████                                                | 1000/2590 [14:16<27:31,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▏                                               | 1001/2590 [14:17<27:51,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▏                                               | 1002/2590 [14:18<29:16,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▏                                               | 1003/2590 [14:19<28:43,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▏                                               | 1004/2590 [14:20<26:47,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▎                                               | 1005/2590 [14:21<26:42,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▎                                               | 1006/2590 [14:22<28:10,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▎                                               | 1007/2590 [14:23<26:54,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 39%|██████████████████████████████▎                                               | 1008/2590 [14:24<27:04,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                               | 1009/2590 [14:25<26:08,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                               | 1010/2590 [14:26<24:01,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                               | 1011/2590 [14:27<25:59,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▍                                               | 1012/2590 [14:28<25:23,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▌                                               | 1013/2590 [14:29<25:51,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▌                                               | 1014/2590 [14:30<27:39,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▌                                               | 1015/2590 [14:31<27:43,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▌                                               | 1016/2590 [14:32<26:25,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▋                                               | 1017/2590 [14:33<25:40,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▋                                               | 1018/2590 [14:34<27:26,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▋                                               | 1019/2590 [14:35<26:57,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▋                                               | 1020/2590 [14:36<26:56,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▋                                               | 1021/2590 [14:37<28:28,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▊                                               | 1022/2590 [14:38<27:34,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 39%|██████████████████████████████▊                                               | 1023/2590 [14:39<26:24,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▊                                               | 1024/2590 [14:41<28:16,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▊                                               | 1025/2590 [14:42<27:36,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▉                                               | 1026/2590 [14:42<25:35,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▉                                               | 1027/2590 [14:43<27:08,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▉                                               | 1028/2590 [14:44<26:10,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|██████████████████████████████▉                                               | 1029/2590 [14:45<26:42,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████                                               | 1030/2590 [14:47<28:49,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████                                               | 1031/2590 [14:48<27:17,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 40%|███████████████████████████████                                               | 1032/2590 [14:49<28:14,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████                                               | 1033/2590 [14:50<31:03,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▏                                              | 1034/2590 [14:52<34:50,  1.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▏                                              | 1035/2590 [14:53<32:06,  1.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▏                                              | 1036/2590 [14:54<30:25,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▏                                              | 1037/2590 [14:55<30:30,  1.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▎                                              | 1038/2590 [14:56<29:00,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▎                                              | 1039/2590 [14:57<28:08,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▎                                              | 1040/2590 [14:58<29:09,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▎                                              | 1041/2590 [14:59<27:45,  1.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▍                                              | 1042/2590 [15:00<26:56,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▍                                              | 1043/2590 [15:02<29:03,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▍                                              | 1044/2590 [15:03<28:22,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▍                                              | 1045/2590 [15:04<27:33,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▌                                              | 1046/2590 [15:05<26:31,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▌                                              | 1047/2590 [15:06<28:33,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 40%|███████████████████████████████▌                                              | 1048/2590 [15:07<27:21,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▌                                              | 1049/2590 [15:08<26:11,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▌                                              | 1050/2590 [15:09<27:32,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▋                                              | 1051/2590 [15:10<26:38,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▋                                              | 1052/2590 [15:11<26:49,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▋                                              | 1053/2590 [15:12<26:09,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▋                                              | 1054/2590 [15:13<27:54,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▊                                              | 1055/2590 [15:14<26:39,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 41%|███████████████████████████████▊                                              | 1056/2590 [15:15<25:57,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▊                                              | 1057/2590 [15:16<27:57,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▊                                              | 1058/2590 [15:17<26:37,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▉                                              | 1059/2590 [15:18<26:48,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▉                                              | 1060/2590 [15:20<27:04,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▉                                              | 1061/2590 [15:20<26:11,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|███████████████████████████████▉                                              | 1062/2590 [15:21<25:15,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████                                              | 1063/2590 [15:22<25:03,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████                                              | 1064/2590 [15:24<27:15,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████                                              | 1065/2590 [15:25<26:48,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████                                              | 1066/2590 [15:26<26:04,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▏                                             | 1067/2590 [15:27<28:09,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▏                                             | 1068/2590 [15:28<26:50,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▏                                             | 1069/2590 [15:29<25:53,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▏                                             | 1070/2590 [15:30<25:46,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▎                                             | 1071/2590 [15:32<37:40,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▎                                             | 1072/2590 [15:34<38:46,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▎                                             | 1073/2590 [15:35<38:33,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 41%|████████████████████████████████▎                                             | 1074/2590 [15:37<35:18,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▎                                             | 1075/2590 [15:38<33:27,  1.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▍                                             | 1076/2590 [15:39<31:17,  1.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▍                                             | 1077/2590 [15:40<29:15,  1.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▍                                             | 1078/2590 [15:41<30:24,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▍                                             | 1079/2590 [15:42<25:38,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 42%|████████████████████████████████▌                                             | 1080/2590 [15:42<23:31,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▌                                             | 1081/2590 [15:43<24:04,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▌                                             | 1082/2590 [15:45<25:14,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▌                                             | 1083/2590 [15:45<24:11,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▋                                             | 1084/2590 [15:46<23:15,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▋                                             | 1085/2590 [15:47<21:25,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▋                                             | 1086/2590 [15:48<24:17,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▋                                             | 1087/2590 [15:49<23:48,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▊                                             | 1088/2590 [15:50<22:52,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▊                                             | 1089/2590 [15:51<22:47,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▊                                             | 1090/2590 [15:52<22:44,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▊                                             | 1091/2590 [15:52<21:01,  1.19it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▉                                             | 1092/2590 [15:53<21:17,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▉                                             | 1093/2590 [15:54<21:23,  1.17it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▉                                             | 1094/2590 [15:55<23:07,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|████████████████████████████████▉                                             | 1095/2590 [15:56<24:16,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|█████████████████████████████████                                             | 1096/2590 [15:57<23:45,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|█████████████████████████████████                                             | 1097/2590 [15:58<24:49,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|█████████████████████████████████                                             | 1098/2590 [16:00<30:17,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|█████████████████████████████████                                             | 1099/2590 [16:01<30:14,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 42%|█████████████████████████████████▏                                            | 1100/2590 [16:02<28:12,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▏                                            | 1101/2590 [16:03<26:36,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▏                                            | 1102/2590 [16:04<28:42,  1.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▏                                            | 1103/2590 [16:06<27:49,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 43%|█████████████████████████████████▏                                            | 1104/2590 [16:06<26:17,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▎                                            | 1105/2590 [16:08<27:46,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▎                                            | 1106/2590 [16:09<26:57,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▎                                            | 1107/2590 [16:10<24:49,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▎                                            | 1108/2590 [16:10<22:42,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▍                                            | 1109/2590 [16:11<24:16,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▍                                            | 1110/2590 [16:12<23:23,  1.05it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▍                                            | 1111/2590 [16:13<24:01,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▍                                            | 1112/2590 [16:14<23:59,  1.03it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▌                                            | 1113/2590 [16:15<25:23,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▌                                            | 1114/2590 [16:16<24:38,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▌                                            | 1115/2590 [16:17<23:12,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▌                                            | 1116/2590 [16:18<22:59,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▋                                            | 1117/2590 [16:19<25:52,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▋                                            | 1118/2590 [16:20<25:12,  1.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▋                                            | 1119/2590 [16:21<24:42,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▋                                            | 1120/2590 [16:23<25:57,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▊                                            | 1121/2590 [16:24<25:41,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▊                                            | 1122/2590 [16:25<25:50,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▊                                            | 1123/2590 [16:26<28:01,  1.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▊                                            | 1124/2590 [16:27<26:45,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▉                                            | 1125/2590 [16:28<26:12,  1.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 43%|█████████████████████████████████▉                                            | 1126/2590 [16:29<27:01,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|█████████████████████████████████▉                                            | 1127/2590 [16:31<29:15,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 44%|█████████████████████████████████▉                                            | 1128/2590 [16:32<29:56,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████                                            | 1129/2590 [16:33<27:50,  1.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████                                            | 1130/2590 [16:34<26:52,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████                                            | 1131/2590 [16:35<28:15,  1.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████                                            | 1132/2590 [16:36<27:32,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████                                            | 1133/2590 [16:37<26:29,  1.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▏                                           | 1134/2590 [16:39<30:48,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▏                                           | 1135/2590 [16:40<32:48,  1.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▏                                           | 1136/2590 [16:42<33:00,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▏                                           | 1137/2590 [16:43<31:05,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▎                                           | 1138/2590 [16:44<30:30,  1.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▎                                           | 1139/2590 [16:45<29:04,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▎                                           | 1140/2590 [16:46<26:58,  1.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▎                                           | 1141/2590 [16:47<26:52,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▍                                           | 1142/2590 [16:48<24:24,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▍                                           | 1143/2590 [16:49<22:39,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▍                                           | 1144/2590 [16:50<22:34,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▍                                           | 1145/2590 [16:51<22:46,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▌                                           | 1146/2590 [16:52<22:14,  1.08it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▌                                           | 1147/2590 [16:52<22:34,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▌                                           | 1148/2590 [16:54<23:07,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▌                                           | 1149/2590 [16:54<21:49,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▋                                           | 1150/2590 [16:55<21:58,  1.09it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 44%|██████████████████████████████████▋                                           | 1151/2590 [16:56<22:33,  1.06it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 44%|██████████████████████████████████▋                                           | 1152/2590 [16:57<23:54,  1.00it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▋                                           | 1153/2590 [16:58<21:46,  1.10it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▊                                           | 1154/2590 [16:59<22:24,  1.07it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▊                                           | 1155/2590 [17:00<23:43,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▊                                           | 1156/2590 [17:01<25:26,  1.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▊                                           | 1157/2590 [17:02<24:27,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▊                                           | 1158/2590 [17:03<23:30,  1.02it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▉                                           | 1159/2590 [17:04<25:04,  1.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▉                                           | 1160/2590 [17:05<24:44,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▉                                           | 1161/2590 [17:07<26:14,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▉                                           | 1162/2590 [17:08<27:38,  1.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████                                           | 1163/2590 [17:09<29:46,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████                                           | 1164/2590 [17:10<26:08,  1.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████                                           | 1165/2590 [17:11<24:47,  1.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████                                           | 1166/2590 [17:12<22:51,  1.04it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▏                                          | 1167/2590 [17:13<24:11,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▏                                          | 1168/2590 [17:14<23:24,  1.01it/s]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▏                                          | 1169/2590 [17:15<23:46,  1.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▏                                          | 1170/2590 [17:16<24:11,  1.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▎                                          | 1171/2590 [17:17<26:19,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▎                                          | 1172/2590 [17:18<23:53,  1.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▎                                          | 1173/2590 [17:20<27:45,  1.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▍                                         | 1174/2590 [17:26<1:02:13,  2.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▍                                          | 1175/2590 [17:28<58:46,  2.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 45%|███████████████████████████████████▍                                          | 1176/2590 [17:30<54:24,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|███████████████████████████████████▍                                          | 1177/2590 [17:33<58:32,  2.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 45%|██████████████████████████████████▌                                         | 1178/2590 [17:37<1:09:04,  2.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▌                                         | 1179/2590 [17:40<1:15:13,  3.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▋                                         | 1180/2590 [17:44<1:16:27,  3.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▋                                         | 1181/2590 [17:48<1:25:54,  3.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▋                                         | 1182/2590 [17:51<1:17:03,  3.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▋                                         | 1183/2590 [17:52<1:04:23,  2.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▋                                         | 1184/2590 [17:57<1:17:57,  3.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▊                                         | 1185/2590 [18:00<1:17:37,  3.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|██████████████████████████████████▊                                         | 1186/2590 [18:02<1:06:22,  2.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▋                                          | 1187/2590 [18:03<56:25,  2.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▊                                          | 1188/2590 [18:05<51:21,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▊                                          | 1189/2590 [18:07<49:21,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▊                                          | 1190/2590 [18:10<51:28,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▊                                          | 1191/2590 [18:11<49:16,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▉                                          | 1192/2590 [18:14<53:32,  2.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████                                         | 1193/2590 [18:22<1:33:15,  4.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████                                         | 1194/2590 [18:24<1:21:09,  3.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████                                         | 1195/2590 [18:27<1:15:27,  3.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████                                         | 1196/2590 [18:30<1:12:25,  3.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████                                         | 1197/2590 [18:33<1:11:35,  3.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▏                                        | 1198/2590 [18:36<1:11:33,  3.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▏                                        | 1199/2590 [18:38<1:00:40,  2.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 46%|████████████████████████████████████▏                                         | 1200/2590 [18:39<54:25,  2.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|████████████████████████████████████▏                                         | 1201/2590 [18:41<50:15,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|████████████████████████████████████▏                                         | 1202/2590 [18:43<48:46,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▎                                        | 1203/2590 [18:50<1:19:37,  3.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 46%|███████████████████████████████████▎                                        | 1204/2590 [18:52<1:14:27,  3.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▎                                        | 1205/2590 [18:58<1:30:55,  3.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▍                                        | 1206/2590 [19:02<1:28:53,  3.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▍                                        | 1207/2590 [19:05<1:28:03,  3.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▍                                        | 1208/2590 [19:08<1:17:33,  3.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▍                                        | 1209/2590 [19:11<1:20:02,  3.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▌                                        | 1210/2590 [19:14<1:13:13,  3.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▌                                        | 1211/2590 [19:16<1:05:24,  2.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▌                                        | 1212/2590 [19:18<1:02:36,  2.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▌                                         | 1213/2590 [19:21<59:34,  2.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▌                                        | 1214/2590 [19:23<1:00:30,  2.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▌                                         | 1215/2590 [19:26<59:20,  2.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▌                                         | 1216/2590 [19:28<53:57,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▋                                        | 1217/2590 [19:31<1:01:29,  2.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▋                                        | 1218/2590 [19:35<1:07:09,  2.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|███████████████████████████████████▊                                        | 1219/2590 [19:37<1:00:32,  2.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▋                                         | 1220/2590 [19:39<57:21,  2.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▊                                         | 1221/2590 [19:41<55:55,  2.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▊                                         | 1222/2590 [19:44<56:51,  2.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▊                                         | 1223/2590 [19:46<53:22,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 47%|████████████████████████████████████▊                                         | 1224/2590 [19:48<54:05,  2.38s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▉                                         | 1225/2590 [19:50<48:56,  2.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▉                                         | 1226/2590 [19:52<52:22,  2.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▉                                         | 1227/2590 [19:54<50:29,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|████████████████████████████████████▉                                         | 1228/2590 [19:57<53:19,  2.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|█████████████████████████████████████                                         | 1229/2590 [20:00<56:51,  2.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 47%|█████████████████████████████████████                                         | 1230/2590 [20:03<58:15,  2.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████                                         | 1231/2590 [20:05<55:01,  2.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████                                         | 1232/2590 [20:07<50:12,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▏                                        | 1233/2590 [20:09<53:23,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▏                                        | 1234/2590 [20:11<51:23,  2.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▏                                        | 1235/2590 [20:13<44:22,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▏                                        | 1236/2590 [20:14<44:21,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▎                                        | 1237/2590 [20:17<48:00,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▎                                        | 1238/2590 [20:19<50:11,  2.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▎                                        | 1239/2590 [20:21<44:31,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▎                                        | 1240/2590 [20:22<41:43,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▎                                        | 1241/2590 [20:25<45:06,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▍                                        | 1242/2590 [20:26<41:27,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▍                                        | 1243/2590 [20:27<36:53,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▍                                        | 1244/2590 [20:30<40:37,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▍                                        | 1245/2590 [20:31<40:04,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▌                                        | 1246/2590 [20:32<35:34,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▌                                        | 1247/2590 [20:34<33:45,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 48%|█████████████████████████████████████▌                                        | 1248/2590 [20:35<34:20,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▌                                        | 1249/2590 [20:37<34:25,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▋                                        | 1250/2590 [20:38<33:25,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▋                                        | 1251/2590 [20:40<32:41,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▋                                        | 1252/2590 [20:42<37:01,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▋                                        | 1253/2590 [20:43<35:20,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▊                                        | 1254/2590 [20:45<33:18,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▊                                        | 1255/2590 [20:46<33:42,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 48%|█████████████████████████████████████▊                                        | 1256/2590 [20:48<36:25,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|█████████████████████████████████████▊                                        | 1257/2590 [20:50<39:13,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|█████████████████████████████████████▉                                        | 1258/2590 [20:52<40:55,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|█████████████████████████████████████▉                                        | 1259/2590 [20:54<41:26,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|█████████████████████████████████████▉                                        | 1260/2590 [20:55<36:51,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|█████████████████████████████████████▉                                        | 1261/2590 [20:57<35:28,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████                                        | 1262/2590 [20:58<36:23,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████                                        | 1263/2590 [21:00<34:40,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████                                        | 1264/2590 [21:01<32:48,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████                                        | 1265/2590 [21:03<33:40,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▏                                       | 1266/2590 [21:05<35:19,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▏                                       | 1267/2590 [21:06<33:03,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▏                                       | 1268/2590 [21:07<30:52,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▏                                       | 1269/2590 [21:08<30:49,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▏                                       | 1270/2590 [21:10<32:07,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▎                                       | 1271/2590 [21:11<30:10,  1.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 49%|██████████████████████████████████████▎                                       | 1272/2590 [21:12<29:05,  1.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▎                                       | 1273/2590 [21:14<32:24,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▎                                       | 1274/2590 [21:16<32:20,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▍                                       | 1275/2590 [21:17<30:13,  1.38s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▍                                       | 1276/2590 [21:18<28:07,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▍                                       | 1277/2590 [21:19<28:45,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▍                                       | 1278/2590 [21:21<31:15,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▌                                       | 1279/2590 [21:22<31:42,  1.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▌                                       | 1280/2590 [21:24<31:42,  1.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▌                                       | 1281/2590 [21:26<35:08,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 49%|██████████████████████████████████████▌                                       | 1282/2590 [21:27<32:39,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▋                                       | 1283/2590 [21:28<30:44,  1.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▋                                       | 1284/2590 [21:30<30:17,  1.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▋                                       | 1285/2590 [21:32<35:32,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▋                                       | 1286/2590 [21:33<35:15,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▊                                       | 1287/2590 [21:35<35:01,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▊                                       | 1288/2590 [21:36<32:24,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▊                                       | 1289/2590 [21:38<34:31,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▊                                       | 1290/2590 [21:40<33:59,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▉                                       | 1291/2590 [21:41<34:52,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▉                                       | 1292/2590 [21:43<36:27,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▉                                       | 1293/2590 [21:44<33:22,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|██████████████████████████████████████▉                                       | 1294/2590 [21:46<30:58,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████                                       | 1295/2590 [21:47<29:22,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 50%|███████████████████████████████████████                                       | 1296/2590 [21:49<33:14,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████                                       | 1297/2590 [21:50<30:31,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████                                       | 1298/2590 [21:51<31:23,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████                                       | 1299/2590 [21:53<30:29,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▏                                      | 1300/2590 [21:54<31:53,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▏                                      | 1301/2590 [21:56<31:37,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▏                                      | 1302/2590 [21:58<35:05,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▏                                      | 1303/2590 [22:01<42:14,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▎                                      | 1304/2590 [22:03<46:06,  2.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▎                                      | 1305/2590 [22:05<44:25,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▎                                      | 1306/2590 [22:07<42:23,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 50%|███████████████████████████████████████▎                                      | 1307/2590 [22:10<51:12,  2.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▍                                      | 1308/2590 [22:12<50:25,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▍                                      | 1309/2590 [22:15<50:34,  2.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▍                                      | 1310/2590 [22:17<50:58,  2.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▍                                      | 1311/2590 [22:19<49:43,  2.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▌                                      | 1312/2590 [22:21<46:34,  2.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▌                                      | 1313/2590 [22:23<46:13,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▌                                      | 1314/2590 [22:26<48:54,  2.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▌                                      | 1315/2590 [22:28<46:49,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▋                                      | 1316/2590 [22:31<49:41,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▋                                      | 1317/2590 [22:34<58:52,  2.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▋                                      | 1318/2590 [22:36<51:41,  2.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▋                                      | 1319/2590 [22:37<44:43,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 51%|███████████████████████████████████████▊                                      | 1320/2590 [22:39<41:15,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▊                                      | 1321/2590 [22:41<41:38,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▊                                      | 1322/2590 [22:43<44:22,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▊                                      | 1323/2590 [22:45<41:19,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▊                                      | 1324/2590 [22:47<40:37,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▉                                      | 1325/2590 [22:48<37:35,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▉                                      | 1326/2590 [22:50<38:49,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▉                                      | 1327/2590 [22:52<38:29,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|███████████████████████████████████████▉                                      | 1328/2590 [22:54<37:15,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|████████████████████████████████████████                                      | 1329/2590 [22:56<37:55,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|████████████████████████████████████████                                      | 1330/2590 [22:57<36:10,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|████████████████████████████████████████                                      | 1331/2590 [22:59<34:11,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|████████████████████████████████████████                                      | 1332/2590 [23:01<36:18,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 51%|████████████████████████████████████████▏                                     | 1333/2590 [23:02<34:15,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▏                                     | 1334/2590 [23:06<48:22,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▏                                     | 1335/2590 [23:07<43:28,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▏                                     | 1336/2590 [23:08<35:50,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▎                                     | 1337/2590 [23:09<31:37,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▎                                     | 1338/2590 [23:13<46:23,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▎                                     | 1339/2590 [23:16<48:19,  2.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▎                                     | 1340/2590 [23:18<46:01,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▍                                     | 1341/2590 [23:19<39:33,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▍                                     | 1342/2590 [23:20<34:18,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▍                                     | 1343/2590 [23:21<33:15,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 52%|████████████████████████████████████████▍                                     | 1344/2590 [23:22<29:41,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▌                                     | 1345/2590 [23:23<26:50,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▌                                     | 1346/2590 [23:25<25:31,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▌                                     | 1347/2590 [23:26<24:49,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▌                                     | 1348/2590 [23:27<26:30,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▋                                     | 1349/2590 [23:29<29:52,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▋                                     | 1350/2590 [23:31<30:44,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▋                                     | 1351/2590 [23:33<36:03,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▋                                     | 1352/2590 [23:35<35:20,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▋                                     | 1353/2590 [23:36<35:14,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▊                                     | 1354/2590 [23:38<35:02,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▊                                     | 1355/2590 [23:40<37:46,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▊                                     | 1356/2590 [23:42<35:21,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▊                                     | 1357/2590 [23:43<34:46,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▉                                     | 1358/2590 [23:45<35:08,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 52%|████████████████████████████████████████▉                                     | 1359/2590 [23:47<36:39,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|████████████████████████████████████████▉                                     | 1360/2590 [23:49<37:51,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|████████████████████████████████████████▉                                     | 1361/2590 [23:51<40:46,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████                                     | 1362/2590 [23:53<41:37,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████                                     | 1363/2590 [23:55<38:45,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████                                     | 1364/2590 [23:57<37:29,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████                                     | 1365/2590 [23:59<38:54,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▏                                    | 1366/2590 [24:00<36:40,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▏                                    | 1367/2590 [24:02<35:57,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 53%|█████████████████████████████████████████▏                                    | 1368/2590 [24:03<34:12,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▏                                    | 1369/2590 [24:05<36:09,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▎                                    | 1370/2590 [24:07<36:14,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▎                                    | 1371/2590 [24:09<34:24,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▎                                    | 1372/2590 [24:10<32:53,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▎                                    | 1373/2590 [24:12<36:27,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▍                                    | 1374/2590 [24:14<35:40,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▍                                    | 1375/2590 [24:15<33:55,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▍                                    | 1376/2590 [24:17<34:52,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▍                                    | 1377/2590 [24:19<36:23,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▍                                    | 1378/2590 [24:21<34:16,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▌                                    | 1379/2590 [24:22<33:43,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▌                                    | 1380/2590 [24:24<32:56,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▌                                    | 1381/2590 [24:26<34:59,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▌                                    | 1382/2590 [24:27<33:20,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▋                                    | 1383/2590 [24:29<35:26,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▋                                    | 1384/2590 [24:31<35:01,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 53%|█████████████████████████████████████████▋                                    | 1385/2590 [24:33<38:17,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▋                                    | 1386/2590 [24:35<35:49,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▊                                    | 1387/2590 [24:36<34:28,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▊                                    | 1388/2590 [24:38<32:24,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▊                                    | 1389/2590 [24:40<36:17,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▊                                    | 1390/2590 [24:41<34:04,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▉                                    | 1391/2590 [24:43<32:41,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 54%|█████████████████████████████████████████▉                                    | 1392/2590 [24:45<33:28,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▉                                    | 1393/2590 [24:47<35:35,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|█████████████████████████████████████████▉                                    | 1394/2590 [24:48<34:13,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████                                    | 1395/2590 [24:50<34:25,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████                                    | 1396/2590 [24:52<35:12,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████                                    | 1397/2590 [24:53<33:04,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████                                    | 1398/2590 [24:55<32:32,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▏                                   | 1399/2590 [24:56<31:36,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▏                                   | 1400/2590 [24:57<28:22,  1.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▏                                   | 1401/2590 [24:59<26:51,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▏                                   | 1402/2590 [25:00<26:12,  1.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▎                                   | 1403/2590 [25:01<26:16,  1.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▎                                   | 1404/2590 [25:02<24:23,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▎                                   | 1405/2590 [25:03<23:50,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▎                                   | 1406/2590 [25:04<23:07,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▎                                   | 1407/2590 [25:06<25:42,  1.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▍                                   | 1408/2590 [25:07<24:13,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▍                                   | 1409/2590 [25:08<23:12,  1.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▍                                   | 1410/2590 [25:10<24:53,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 54%|██████████████████████████████████████████▍                                   | 1411/2590 [25:11<25:10,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▌                                   | 1412/2590 [25:12<24:02,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▌                                   | 1413/2590 [25:14<25:17,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▌                                   | 1414/2590 [25:15<23:52,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▌                                   | 1415/2590 [25:16<24:00,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 55%|██████████████████████████████████████████▋                                   | 1416/2590 [25:17<23:56,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▋                                   | 1417/2590 [25:18<25:07,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▋                                   | 1418/2590 [25:20<24:27,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▋                                   | 1419/2590 [25:21<25:04,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▊                                   | 1420/2590 [25:23<26:36,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▊                                   | 1421/2590 [25:24<25:19,  1.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▊                                   | 1422/2590 [25:25<24:24,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▊                                   | 1423/2590 [25:26<24:53,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▉                                   | 1424/2590 [25:28<25:54,  1.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▉                                   | 1425/2590 [25:29<24:49,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▉                                   | 1426/2590 [25:30<23:24,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|██████████████████████████████████████████▉                                   | 1427/2590 [25:31<22:11,  1.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████                                   | 1428/2590 [25:32<24:44,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████                                   | 1429/2590 [25:34<23:30,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████                                   | 1430/2590 [25:35<22:49,  1.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████                                   | 1431/2590 [25:36<22:41,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▏                                  | 1432/2590 [25:37<23:12,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▏                                  | 1433/2590 [25:38<24:28,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▏                                  | 1434/2590 [25:40<23:30,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▏                                  | 1435/2590 [25:40<21:19,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▏                                  | 1436/2590 [25:42<21:23,  1.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 55%|███████████████████████████████████████████▎                                  | 1437/2590 [25:43<24:14,  1.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▎                                  | 1438/2590 [25:44<23:17,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▎                                  | 1439/2590 [25:45<23:12,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 56%|███████████████████████████████████████████▎                                  | 1440/2590 [25:47<22:28,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▍                                  | 1441/2590 [25:48<25:27,  1.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▍                                  | 1442/2590 [25:49<24:10,  1.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▍                                  | 1443/2590 [25:50<23:25,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▍                                  | 1444/2590 [25:52<22:59,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▌                                  | 1445/2590 [25:53<25:36,  1.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▌                                  | 1446/2590 [25:54<24:18,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▌                                  | 1447/2590 [25:56<23:41,  1.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▌                                  | 1448/2590 [25:57<24:34,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▋                                  | 1449/2590 [25:58<24:23,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▋                                  | 1450/2590 [26:00<24:27,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▋                                  | 1451/2590 [26:01<25:34,  1.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▋                                  | 1452/2590 [26:03<29:07,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▊                                  | 1453/2590 [26:04<27:46,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▊                                  | 1454/2590 [26:05<25:42,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▊                                  | 1455/2590 [26:07<24:14,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▊                                  | 1456/2590 [26:08<25:40,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▉                                  | 1457/2590 [26:09<25:09,  1.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▉                                  | 1458/2590 [26:10<24:02,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▉                                  | 1459/2590 [26:12<23:05,  1.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▉                                  | 1460/2590 [26:13<24:20,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|███████████████████████████████████████████▉                                  | 1461/2590 [26:14<24:10,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|████████████████████████████████████████████                                  | 1462/2590 [26:16<24:06,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 56%|████████████████████████████████████████████                                  | 1463/2590 [26:17<25:48,  1.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 57%|████████████████████████████████████████████                                  | 1464/2590 [26:18<24:49,  1.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████                                  | 1465/2590 [26:20<24:31,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▏                                 | 1466/2590 [26:21<23:19,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▏                                 | 1467/2590 [26:22<25:38,  1.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▏                                 | 1468/2590 [26:25<31:50,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▏                                 | 1469/2590 [26:27<31:43,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▎                                 | 1470/2590 [26:28<30:56,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▎                                 | 1471/2590 [26:30<32:14,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▎                                 | 1472/2590 [26:32<34:52,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▎                                 | 1473/2590 [26:34<32:23,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▍                                 | 1474/2590 [26:35<28:35,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▍                                 | 1475/2590 [26:37<30:18,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▍                                 | 1476/2590 [26:39<32:49,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▍                                 | 1477/2590 [26:40<31:22,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▌                                 | 1478/2590 [26:42<31:56,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▌                                 | 1479/2590 [26:44<31:37,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▌                                 | 1480/2590 [26:47<38:28,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▌                                 | 1481/2590 [26:49<38:27,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▋                                 | 1482/2590 [26:50<33:20,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▋                                 | 1483/2590 [26:51<29:52,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▋                                 | 1484/2590 [26:52<26:45,  1.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▋                                 | 1485/2590 [26:53<24:06,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▊                                 | 1486/2590 [26:54<23:46,  1.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▊                                 | 1487/2590 [26:55<22:11,  1.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 57%|████████████████████████████████████████████▊                                 | 1488/2590 [26:56<20:46,  1.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 57%|████████████████████████████████████████████▊                                 | 1489/2590 [26:58<25:37,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|████████████████████████████████████████████▊                                 | 1490/2590 [27:01<32:47,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|████████████████████████████████████████████▉                                 | 1491/2590 [27:02<30:57,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|████████████████████████████████████████████▉                                 | 1492/2590 [27:04<29:26,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|████████████████████████████████████████████▉                                 | 1493/2590 [27:05<27:58,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|████████████████████████████████████████████▉                                 | 1494/2590 [27:07<29:42,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████                                 | 1495/2590 [27:08<28:14,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████                                 | 1496/2590 [27:10<29:42,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████                                 | 1497/2590 [27:13<33:57,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████                                 | 1498/2590 [27:14<31:55,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▏                                | 1499/2590 [27:16<30:28,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▏                                | 1500/2590 [27:17<28:11,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▏                                | 1501/2590 [27:19<30:57,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▏                                | 1502/2590 [27:20<28:32,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▎                                | 1503/2590 [27:22<27:29,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▎                                | 1504/2590 [27:23<26:21,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▎                                | 1505/2590 [27:25<29:05,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▎                                | 1506/2590 [27:26<27:46,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▍                                | 1507/2590 [27:27<25:38,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▍                                | 1508/2590 [27:29<25:41,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▍                                | 1509/2590 [27:30<25:58,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▍                                | 1510/2590 [27:32<28:31,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▌                                | 1511/2590 [27:34<27:40,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 58%|█████████████████████████████████████████████▌                                | 1512/2590 [27:35<25:35,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▌                                | 1513/2590 [27:36<25:32,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▌                                | 1514/2590 [27:38<27:07,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 58%|█████████████████████████████████████████████▋                                | 1515/2590 [27:39<26:19,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▋                                | 1516/2590 [27:41<27:09,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▋                                | 1517/2590 [27:42<26:53,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▋                                | 1518/2590 [27:44<28:24,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▋                                | 1519/2590 [27:46<28:05,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▊                                | 1520/2590 [27:47<27:20,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▊                                | 1521/2590 [27:49<26:40,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▊                                | 1522/2590 [27:51<29:58,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▊                                | 1523/2590 [27:52<28:20,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▉                                | 1524/2590 [27:54<28:20,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▉                                | 1525/2590 [27:55<26:34,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▉                                | 1526/2590 [27:57<26:59,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|█████████████████████████████████████████████▉                                | 1527/2590 [27:58<28:30,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████                                | 1528/2590 [28:00<26:30,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████                                | 1529/2590 [28:01<26:02,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████                                | 1530/2590 [28:03<26:31,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████                                | 1531/2590 [28:04<28:10,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▏                               | 1532/2590 [28:06<25:24,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▏                               | 1533/2590 [28:07<26:15,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▏                               | 1534/2590 [28:08<24:39,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▏                               | 1535/2590 [28:09<22:59,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 59%|██████████████████████████████████████████████▎                               | 1536/2590 [28:11<26:09,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▎                               | 1537/2590 [28:13<26:17,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▎                               | 1538/2590 [28:14<25:35,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▎                               | 1539/2590 [28:16<25:15,  1.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▍                               | 1540/2590 [28:17<24:23,  1.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 59%|██████████████████████████████████████████████▍                               | 1541/2590 [28:19<30:09,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▍                               | 1542/2590 [28:21<30:37,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▍                               | 1543/2590 [28:23<29:35,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▍                               | 1544/2590 [28:24<28:46,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▌                               | 1545/2590 [28:26<29:27,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▌                               | 1546/2590 [28:27<27:49,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▌                               | 1547/2590 [28:29<27:53,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▌                               | 1548/2590 [28:30<26:23,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▋                               | 1549/2590 [28:32<26:17,  1.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▋                               | 1550/2590 [28:34<28:23,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▋                               | 1551/2590 [28:35<27:27,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▋                               | 1552/2590 [28:37<25:57,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▊                               | 1553/2590 [28:38<25:17,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▊                               | 1554/2590 [28:40<28:14,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▊                               | 1555/2590 [28:41<27:10,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▊                               | 1556/2590 [28:43<26:29,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▉                               | 1557/2590 [28:45<28:45,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▉                               | 1558/2590 [28:46<27:34,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|██████████████████████████████████████████████▉                               | 1559/2590 [28:48<26:21,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 60%|██████████████████████████████████████████████▉                               | 1560/2590 [28:49<25:57,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████                               | 1561/2590 [28:51<28:41,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████                               | 1562/2590 [28:53<27:12,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████                               | 1563/2590 [28:54<25:45,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████                               | 1564/2590 [28:56<26:06,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████▏                              | 1565/2590 [28:57<25:24,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 60%|███████████████████████████████████████████████▏                              | 1566/2590 [28:59<26:31,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▏                              | 1567/2590 [29:00<25:19,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▏                              | 1568/2590 [29:01<25:38,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▎                              | 1569/2590 [29:03<24:56,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▎                              | 1570/2590 [29:04<25:16,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▎                              | 1571/2590 [29:06<27:55,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▎                              | 1572/2590 [29:08<26:56,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▎                              | 1573/2590 [29:09<25:56,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▍                              | 1574/2590 [29:10<24:04,  1.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▍                              | 1575/2590 [29:13<27:33,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▍                              | 1576/2590 [29:14<26:23,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▍                              | 1577/2590 [29:15<25:51,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▌                              | 1578/2590 [29:17<25:57,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▌                              | 1579/2590 [29:19<27:32,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▌                              | 1580/2590 [29:20<26:23,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▌                              | 1581/2590 [29:22<26:35,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▋                              | 1582/2590 [29:24<28:50,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▋                              | 1583/2590 [29:26<31:58,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 61%|███████████████████████████████████████████████▋                              | 1584/2590 [29:28<32:01,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▋                              | 1585/2590 [29:29<28:30,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▊                              | 1586/2590 [29:31<27:52,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▊                              | 1587/2590 [29:33<28:47,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▊                              | 1588/2590 [29:34<27:40,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▊                              | 1589/2590 [29:36<26:07,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▉                              | 1590/2590 [29:37<25:25,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▉                              | 1591/2590 [29:39<27:36,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 61%|███████████████████████████████████████████████▉                              | 1592/2590 [29:41<26:39,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|███████████████████████████████████████████████▉                              | 1593/2590 [29:42<26:02,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████                              | 1594/2590 [29:44<28:49,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████                              | 1595/2590 [29:46<27:07,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████                              | 1596/2590 [29:47<26:19,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████                              | 1597/2590 [29:49<25:46,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▏                             | 1598/2590 [29:51<28:01,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▏                             | 1599/2590 [29:52<26:56,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▏                             | 1600/2590 [29:53<25:46,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▏                             | 1601/2590 [29:55<24:16,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▏                             | 1602/2590 [29:57<26:27,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▎                             | 1603/2590 [29:58<25:48,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▎                             | 1604/2590 [29:59<24:53,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▎                             | 1605/2590 [30:01<25:41,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▎                             | 1606/2590 [30:03<27:32,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▍                             | 1607/2590 [30:04<25:49,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 62%|████████████████████████████████████████████████▍                             | 1608/2590 [30:06<25:59,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▍                             | 1609/2590 [30:07<25:05,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▍                             | 1610/2590 [30:09<26:23,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▌                             | 1611/2590 [30:11<25:48,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▌                             | 1612/2590 [30:12<24:28,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▌                             | 1613/2590 [30:13<23:51,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▌                             | 1614/2590 [30:15<23:44,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▋                             | 1615/2590 [30:17<26:08,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▋                             | 1616/2590 [30:18<24:30,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▋                             | 1617/2590 [30:20<23:43,  1.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 62%|████████████████████████████████████████████████▋                             | 1618/2590 [30:21<24:02,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▊                             | 1619/2590 [30:23<26:54,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▊                             | 1620/2590 [30:25<27:05,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▊                             | 1621/2590 [30:26<25:54,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▊                             | 1622/2590 [30:28<24:14,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▉                             | 1623/2590 [30:29<24:20,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▉                             | 1624/2590 [30:31<28:47,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▉                             | 1625/2590 [30:34<31:06,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▉                             | 1626/2590 [30:35<29:23,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|████████████████████████████████████████████████▉                             | 1627/2590 [30:37<27:22,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████                             | 1628/2590 [30:39<29:41,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████                             | 1629/2590 [30:40<27:51,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████                             | 1630/2590 [30:42<26:10,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████                             | 1631/2590 [30:43<25:59,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 63%|█████████████████████████████████████████████████▏                            | 1632/2590 [30:45<27:12,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▏                            | 1633/2590 [30:47<25:28,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▏                            | 1634/2590 [30:48<24:06,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▏                            | 1635/2590 [30:49<23:55,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▎                            | 1636/2590 [30:51<25:47,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▎                            | 1637/2590 [30:53<25:10,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▎                            | 1638/2590 [30:54<25:19,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▎                            | 1639/2590 [30:56<23:57,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▍                            | 1640/2590 [30:57<21:18,  1.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▍                            | 1641/2590 [30:59<23:14,  1.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▍                            | 1642/2590 [31:00<24:12,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▍                            | 1643/2590 [31:02<27:23,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 63%|█████████████████████████████████████████████████▌                            | 1644/2590 [31:04<25:57,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▌                            | 1645/2590 [31:06<28:38,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▌                            | 1646/2590 [31:07<26:28,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▌                            | 1647/2590 [31:09<25:29,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▋                            | 1648/2590 [31:11<25:21,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▋                            | 1649/2590 [31:12<26:45,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▋                            | 1650/2590 [31:14<25:41,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▋                            | 1651/2590 [31:16<25:30,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▊                            | 1652/2590 [31:17<24:50,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▊                            | 1653/2590 [31:19<26:16,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▊                            | 1654/2590 [31:20<24:55,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▊                            | 1655/2590 [31:22<24:48,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 64%|█████████████████████████████████████████████████▊                            | 1656/2590 [31:23<24:02,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▉                            | 1657/2590 [31:25<23:31,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▉                            | 1658/2590 [31:27<25:41,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▉                            | 1659/2590 [31:28<24:27,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|█████████████████████████████████████████████████▉                            | 1660/2590 [31:30<24:01,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████                            | 1661/2590 [31:32<26:28,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████                            | 1662/2590 [31:35<31:59,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████                            | 1663/2590 [31:39<41:28,  2.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████                            | 1664/2590 [31:40<37:02,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▏                           | 1665/2590 [31:42<32:35,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▏                           | 1666/2590 [31:44<33:54,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▏                           | 1667/2590 [31:46<30:54,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▏                           | 1668/2590 [31:47<27:48,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▎                           | 1669/2590 [31:49<27:18,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 64%|██████████████████████████████████████████████████▎                           | 1670/2590 [31:50<26:00,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▎                           | 1671/2590 [31:52<27:22,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▎                           | 1672/2590 [31:54<25:24,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▍                           | 1673/2590 [31:55<24:37,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▍                           | 1674/2590 [31:57<23:06,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▍                           | 1675/2590 [31:58<24:45,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▍                           | 1676/2590 [32:00<24:04,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▌                           | 1677/2590 [32:01<23:21,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▌                           | 1678/2590 [32:03<23:30,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▌                           | 1679/2590 [32:04<23:21,  1.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 65%|██████████████████████████████████████████████████▌                           | 1680/2590 [32:07<25:45,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▌                           | 1681/2590 [32:08<23:31,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▋                           | 1682/2590 [32:09<22:27,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▋                           | 1683/2590 [32:11<24:37,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▋                           | 1684/2590 [32:13<23:52,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▋                           | 1685/2590 [32:15<25:49,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▊                           | 1686/2590 [32:16<26:03,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▊                           | 1687/2590 [32:18<25:16,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▊                           | 1688/2590 [32:19<24:58,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▊                           | 1689/2590 [32:22<29:15,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▉                           | 1690/2590 [32:23<26:08,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▉                           | 1691/2590 [32:25<25:20,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▉                           | 1692/2590 [32:27<25:18,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|██████████████████████████████████████████████████▉                           | 1693/2590 [32:28<25:21,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|███████████████████████████████████████████████████                           | 1694/2590 [32:30<27:04,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|███████████████████████████████████████████████████                           | 1695/2590 [32:32<26:31,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 65%|███████████████████████████████████████████████████                           | 1696/2590 [32:34<25:48,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████                           | 1697/2590 [32:35<25:03,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▏                          | 1698/2590 [32:38<27:45,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▏                          | 1699/2590 [32:39<26:26,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▏                          | 1700/2590 [32:41<26:58,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▏                          | 1701/2590 [32:43<28:38,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▎                          | 1702/2590 [32:46<31:34,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▎                          | 1703/2590 [32:48<29:17,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 66%|███████████████████████████████████████████████████▎                          | 1704/2590 [32:49<28:04,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▎                          | 1705/2590 [32:51<27:07,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▍                          | 1706/2590 [32:53<28:29,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▍                          | 1707/2590 [32:55<28:44,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▍                          | 1708/2590 [32:57<26:38,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▍                          | 1709/2590 [32:58<24:47,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▍                          | 1710/2590 [33:00<25:50,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▌                          | 1711/2590 [33:02<25:22,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▌                          | 1712/2590 [33:03<24:42,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▌                          | 1713/2590 [33:05<24:42,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▌                          | 1714/2590 [33:07<24:38,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▋                          | 1715/2590 [33:08<25:51,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▋                          | 1716/2590 [33:10<26:03,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▋                          | 1717/2590 [33:12<24:59,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▋                          | 1718/2590 [33:13<24:05,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▊                          | 1719/2590 [33:16<27:04,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▊                          | 1720/2590 [33:17<25:28,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▊                          | 1721/2590 [33:19<25:03,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 66%|███████████████████████████████████████████████████▊                          | 1722/2590 [33:21<25:28,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|███████████████████████████████████████████████████▉                          | 1723/2590 [33:23<27:19,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|███████████████████████████████████████████████████▉                          | 1724/2590 [33:24<25:41,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|███████████████████████████████████████████████████▉                          | 1725/2590 [33:26<25:00,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|███████████████████████████████████████████████████▉                          | 1726/2590 [33:28<24:33,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████                          | 1727/2590 [33:30<26:35,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 67%|████████████████████████████████████████████████████                          | 1728/2590 [33:32<26:41,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████                          | 1729/2590 [33:33<25:15,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████                          | 1730/2590 [33:35<24:27,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▏                         | 1731/2590 [33:37<26:46,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▏                         | 1732/2590 [33:39<25:44,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▏                         | 1733/2590 [33:40<23:59,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▏                         | 1734/2590 [33:42<23:47,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▎                         | 1735/2590 [33:44<26:04,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▎                         | 1736/2590 [33:46<25:09,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▎                         | 1737/2590 [33:47<24:59,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▎                         | 1738/2590 [33:48<22:08,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▎                         | 1739/2590 [33:50<22:32,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▍                         | 1740/2590 [33:53<27:33,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▍                         | 1741/2590 [33:55<27:49,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▍                         | 1742/2590 [33:57<26:38,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▍                         | 1743/2590 [33:59<26:59,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▌                         | 1744/2590 [34:01<27:55,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▌                         | 1745/2590 [34:02<26:17,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▌                         | 1746/2590 [34:04<26:01,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▌                         | 1747/2590 [34:06<27:38,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 67%|████████████████████████████████████████████████████▋                         | 1748/2590 [34:08<26:11,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▋                         | 1749/2590 [34:10<25:54,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▋                         | 1750/2590 [34:11<24:47,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▋                         | 1751/2590 [34:14<26:43,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 68%|████████████████████████████████████████████████████▊                         | 1752/2590 [34:15<26:13,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▊                         | 1753/2590 [34:17<24:51,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▊                         | 1754/2590 [34:19<23:35,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▊                         | 1755/2590 [34:21<25:38,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▉                         | 1756/2590 [34:22<24:18,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▉                         | 1757/2590 [34:24<23:57,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▉                         | 1758/2590 [34:26<23:29,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|████████████████████████████████████████████████████▉                         | 1759/2590 [34:27<22:58,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████                         | 1760/2590 [34:29<25:14,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████                         | 1761/2590 [34:31<23:55,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████                         | 1762/2590 [34:32<23:12,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████                         | 1763/2590 [34:34<23:09,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████                         | 1764/2590 [34:36<25:56,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▏                        | 1765/2590 [34:38<24:47,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▏                        | 1766/2590 [34:40<24:00,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▏                        | 1767/2590 [34:41<23:02,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▏                        | 1768/2590 [34:43<22:48,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▎                        | 1769/2590 [34:45<24:26,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▎                        | 1770/2590 [34:46<23:25,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▎                        | 1771/2590 [34:48<23:37,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▎                        | 1772/2590 [34:50<23:18,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▍                        | 1773/2590 [34:52<24:57,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 68%|█████████████████████████████████████████████████████▍                        | 1774/2590 [34:54<24:55,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▍                        | 1775/2590 [34:55<24:12,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 69%|█████████████████████████████████████████████████████▍                        | 1776/2590 [34:57<23:42,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▌                        | 1777/2590 [35:00<26:57,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▌                        | 1778/2590 [35:02<27:42,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▌                        | 1779/2590 [35:04<28:13,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▌                        | 1780/2590 [35:06<25:56,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▋                        | 1781/2590 [35:08<26:56,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▋                        | 1782/2590 [35:10<25:57,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▋                        | 1783/2590 [35:11<24:58,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▋                        | 1784/2590 [35:13<26:13,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▊                        | 1785/2590 [35:15<24:43,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▊                        | 1786/2590 [35:17<24:57,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▊                        | 1787/2590 [35:19<24:11,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▊                        | 1788/2590 [35:21<25:56,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▉                        | 1789/2590 [35:22<24:19,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▉                        | 1790/2590 [35:24<23:39,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▉                        | 1791/2590 [35:26<23:25,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▉                        | 1792/2590 [35:27<22:49,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|█████████████████████████████████████████████████████▉                        | 1793/2590 [35:29<24:06,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████                        | 1794/2590 [35:31<24:17,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████                        | 1795/2590 [35:33<22:59,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████                        | 1796/2590 [35:34<22:19,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████                        | 1797/2590 [35:37<24:39,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████▏                       | 1798/2590 [35:38<23:18,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 69%|██████████████████████████████████████████████████████▏                       | 1799/2590 [35:40<21:56,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 69%|██████████████████████████████████████████████████████▏                       | 1800/2590 [35:41<20:41,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▏                       | 1801/2590 [35:43<21:33,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▎                       | 1802/2590 [35:45<23:51,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▎                       | 1803/2590 [35:47<23:38,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▎                       | 1804/2590 [35:48<22:32,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▎                       | 1805/2590 [35:50<22:26,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▍                       | 1806/2590 [35:52<24:51,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▍                       | 1807/2590 [35:54<23:56,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▍                       | 1808/2590 [35:56<22:52,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▍                       | 1809/2590 [35:57<22:41,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▌                       | 1810/2590 [35:59<24:21,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▌                       | 1811/2590 [36:01<22:47,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▌                       | 1812/2590 [36:03<21:55,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▌                       | 1813/2590 [36:04<22:53,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▋                       | 1814/2590 [36:07<26:38,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▋                       | 1815/2590 [36:09<26:20,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▋                       | 1816/2590 [36:11<24:33,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▋                       | 1817/2590 [36:12<23:29,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▊                       | 1818/2590 [36:15<25:46,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▊                       | 1819/2590 [36:16<24:21,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▊                       | 1820/2590 [36:18<23:14,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▊                       | 1821/2590 [36:20<23:27,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▊                       | 1822/2590 [36:22<22:31,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▉                       | 1823/2590 [36:24<23:59,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 70%|██████████████████████████████████████████████████████▉                       | 1824/2590 [36:25<22:41,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 70%|██████████████████████████████████████████████████████▉                       | 1825/2590 [36:27<22:18,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|██████████████████████████████████████████████████████▉                       | 1826/2590 [36:29<22:23,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████                       | 1827/2590 [36:31<25:29,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████                       | 1828/2590 [36:33<24:08,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████                       | 1829/2590 [36:35<23:22,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████                       | 1830/2590 [36:36<22:50,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▏                      | 1831/2590 [36:40<29:55,  2.37s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▏                      | 1832/2590 [36:43<31:46,  2.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▏                      | 1833/2590 [36:45<31:40,  2.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▏                      | 1834/2590 [36:48<33:15,  2.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▎                      | 1835/2590 [36:50<29:43,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▎                      | 1836/2590 [36:52<28:59,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▎                      | 1837/2590 [36:54<26:28,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▎                      | 1838/2590 [36:56<25:18,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▍                      | 1839/2590 [36:58<27:40,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▍                      | 1840/2590 [37:00<26:47,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▍                      | 1841/2590 [37:02<25:35,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▍                      | 1842/2590 [37:04<24:17,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▌                      | 1843/2590 [37:06<23:30,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▌                      | 1844/2590 [37:08<25:21,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▌                      | 1845/2590 [37:10<23:53,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▌                      | 1846/2590 [37:11<22:40,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▌                      | 1847/2590 [37:13<22:17,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 71%|███████████████████████████████████████████████████████▋                      | 1848/2590 [37:15<23:58,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▋                      | 1849/2590 [37:18<26:45,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▋                      | 1850/2590 [37:20<25:08,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 71%|███████████████████████████████████████████████████████▋                      | 1851/2590 [37:21<23:39,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▊                      | 1852/2590 [37:23<22:20,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▊                      | 1853/2590 [37:24<20:56,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▊                      | 1854/2590 [37:27<22:59,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▊                      | 1855/2590 [37:28<22:01,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▉                      | 1856/2590 [37:30<21:10,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▉                      | 1857/2590 [37:31<20:15,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▉                      | 1858/2590 [37:33<21:54,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|███████████████████████████████████████████████████████▉                      | 1859/2590 [37:35<22:01,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████                      | 1860/2590 [37:37<21:24,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████                      | 1861/2590 [37:38<20:11,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████                      | 1862/2590 [37:40<20:02,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████                      | 1863/2590 [37:42<22:43,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▏                     | 1864/2590 [37:44<21:57,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▏                     | 1865/2590 [37:46<22:16,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▏                     | 1866/2590 [37:48<23:30,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▏                     | 1867/2590 [37:50<22:41,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▎                     | 1868/2590 [37:52<22:52,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▎                     | 1869/2590 [37:53<21:39,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▎                     | 1870/2590 [37:56<23:30,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▎                     | 1871/2590 [37:58<22:46,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 72%|████████████████████████████████████████████████████████▍                     | 1872/2590 [37:59<21:47,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▍                     | 1873/2590 [38:01<20:17,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▍                     | 1874/2590 [38:02<20:19,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▍                     | 1875/2590 [38:05<22:14,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▍                     | 1876/2590 [38:06<21:33,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 72%|████████████████████████████████████████████████████████▌                     | 1877/2590 [38:08<21:18,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▌                     | 1878/2590 [38:10<20:50,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▌                     | 1879/2590 [38:12<22:28,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▌                     | 1880/2590 [38:14<22:05,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▋                     | 1881/2590 [38:15<21:11,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▋                     | 1882/2590 [38:17<20:41,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▋                     | 1883/2590 [38:19<23:02,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▋                     | 1884/2590 [38:21<22:33,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▊                     | 1885/2590 [38:23<23:21,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▊                     | 1886/2590 [38:25<22:59,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▊                     | 1887/2590 [38:27<22:11,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▊                     | 1888/2590 [38:30<24:54,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▉                     | 1889/2590 [38:32<25:22,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▉                     | 1890/2590 [38:33<22:28,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▉                     | 1891/2590 [38:35<21:37,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|████████████████████████████████████████████████████████▉                     | 1892/2590 [38:37<23:11,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████                     | 1893/2590 [38:39<21:59,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████                     | 1894/2590 [38:41<21:25,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████                     | 1895/2590 [38:42<19:55,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 73%|█████████████████████████████████████████████████████████                     | 1896/2590 [38:44<19:48,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▏                    | 1897/2590 [38:46<21:54,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▏                    | 1898/2590 [38:47<19:36,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▏                    | 1899/2590 [38:49<18:31,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▏                    | 1900/2590 [38:50<18:38,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▎                    | 1901/2590 [38:52<19:18,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▎                    | 1902/2590 [38:54<19:07,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 73%|█████████████████████████████████████████████████████████▎                    | 1903/2590 [38:56<19:59,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▎                    | 1904/2590 [38:57<19:04,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▎                    | 1905/2590 [38:59<18:09,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▍                    | 1906/2590 [39:00<18:13,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▍                    | 1907/2590 [39:02<18:46,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▍                    | 1908/2590 [39:04<21:05,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▍                    | 1909/2590 [39:06<20:21,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▌                    | 1910/2590 [39:08<20:17,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▌                    | 1911/2590 [39:09<19:15,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▌                    | 1912/2590 [39:11<18:01,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▌                    | 1913/2590 [39:13<20:16,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▋                    | 1914/2590 [39:15<19:38,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▋                    | 1915/2590 [39:16<19:31,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▋                    | 1916/2590 [39:18<18:04,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▋                    | 1917/2590 [39:20<19:46,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▊                    | 1918/2590 [39:21<19:07,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▊                    | 1919/2590 [39:23<18:44,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 74%|█████████████████████████████████████████████████████████▊                    | 1920/2590 [39:24<17:47,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▊                    | 1921/2590 [39:26<16:35,  1.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▉                    | 1922/2590 [39:28<19:14,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▉                    | 1923/2590 [39:30<20:54,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▉                    | 1924/2590 [39:32<21:21,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|█████████████████████████████████████████████████████████▉                    | 1925/2590 [39:34<19:59,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|██████████████████████████████████████████████████████████                    | 1926/2590 [39:36<22:09,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|██████████████████████████████████████████████████████████                    | 1927/2590 [39:38<21:24,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|██████████████████████████████████████████████████████████                    | 1928/2590 [39:40<20:54,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 74%|██████████████████████████████████████████████████████████                    | 1929/2590 [39:41<19:37,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████                    | 1930/2590 [39:43<18:35,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▏                   | 1931/2590 [39:45<21:02,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▏                   | 1932/2590 [39:47<20:16,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▏                   | 1933/2590 [39:49<19:45,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▏                   | 1934/2590 [39:50<19:53,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▎                   | 1935/2590 [39:52<19:20,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▎                   | 1936/2590 [39:54<21:06,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▎                   | 1937/2590 [39:56<20:21,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▎                   | 1938/2590 [39:58<19:44,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▍                   | 1939/2590 [39:59<19:14,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▍                   | 1940/2590 [40:02<21:12,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▍                   | 1941/2590 [40:03<19:55,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▍                   | 1942/2590 [40:05<19:32,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▌                   | 1943/2590 [40:07<19:30,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 75%|██████████████████████████████████████████████████████████▌                   | 1944/2590 [40:09<20:51,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▌                   | 1945/2590 [40:11<20:04,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▌                   | 1946/2590 [40:13<19:46,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▋                   | 1947/2590 [40:14<19:36,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▋                   | 1948/2590 [40:16<18:58,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▋                   | 1949/2590 [40:18<20:50,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▋                   | 1950/2590 [40:20<20:05,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▊                   | 1951/2590 [40:22<19:27,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▊                   | 1952/2590 [40:24<19:21,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▊                   | 1953/2590 [40:26<20:47,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▊                   | 1954/2590 [40:28<19:25,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 75%|██████████████████████████████████████████████████████████▉                   | 1955/2590 [40:30<20:07,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|██████████████████████████████████████████████████████████▉                   | 1956/2590 [40:31<19:45,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|██████████████████████████████████████████████████████████▉                   | 1957/2590 [40:34<22:50,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|██████████████████████████████████████████████████████████▉                   | 1958/2590 [40:37<23:11,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|██████████████████████████████████████████████████████████▉                   | 1959/2590 [40:38<21:19,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████                   | 1960/2590 [40:40<20:49,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████                   | 1961/2590 [40:42<21:42,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████                   | 1962/2590 [40:44<20:37,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████                   | 1963/2590 [40:46<19:35,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▏                  | 1964/2590 [40:47<18:48,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▏                  | 1965/2590 [40:49<18:18,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▏                  | 1966/2590 [40:51<20:29,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▏                  | 1967/2590 [40:53<19:14,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 76%|███████████████████████████████████████████████████████████▎                  | 1968/2590 [40:55<19:24,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▎                  | 1969/2590 [40:56<18:21,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▎                  | 1970/2590 [40:59<19:57,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▎                  | 1971/2590 [41:01<20:00,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▍                  | 1972/2590 [41:02<19:13,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▍                  | 1973/2590 [41:04<18:43,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▍                  | 1974/2590 [41:06<17:38,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▍                  | 1975/2590 [41:08<19:19,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▌                  | 1976/2590 [41:09<18:25,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▌                  | 1977/2590 [41:11<18:26,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▌                  | 1978/2590 [41:13<18:02,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▌                  | 1979/2590 [41:15<19:37,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▋                  | 1980/2590 [41:17<19:04,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 76%|███████████████████████████████████████████████████████████▋                  | 1981/2590 [41:19<18:30,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▋                  | 1982/2590 [41:20<17:58,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▋                  | 1983/2590 [41:22<18:06,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▋                  | 1984/2590 [41:24<17:42,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▊                  | 1985/2590 [41:26<19:23,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▊                  | 1986/2590 [41:28<19:14,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▊                  | 1987/2590 [41:30<18:45,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▊                  | 1988/2590 [41:32<18:53,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▉                  | 1989/2590 [41:34<20:48,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▉                  | 1990/2590 [41:36<19:44,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|███████████████████████████████████████████████████████████▉                  | 1991/2590 [41:38<18:56,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 77%|███████████████████████████████████████████████████████████▉                  | 1992/2590 [41:40<19:48,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████                  | 1993/2590 [41:43<22:49,  2.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████                  | 1994/2590 [41:45<21:45,  2.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████                  | 1995/2590 [41:47<20:17,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████                  | 1996/2590 [41:48<19:34,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▏                 | 1997/2590 [41:50<19:21,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▏                 | 1998/2590 [41:53<20:28,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▏                 | 1999/2590 [41:55<20:10,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▏                 | 2000/2590 [41:56<19:24,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▎                 | 2001/2590 [41:58<18:21,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▎                 | 2002/2590 [42:01<20:46,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▎                 | 2003/2590 [42:02<19:21,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▎                 | 2004/2590 [42:04<18:26,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▍                 | 2005/2590 [42:06<18:21,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▍                 | 2006/2590 [42:08<17:53,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 77%|████████████████████████████████████████████████████████████▍                 | 2007/2590 [42:10<19:03,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▍                 | 2008/2590 [42:12<18:48,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▌                 | 2009/2590 [42:14<18:05,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▌                 | 2010/2590 [42:15<17:16,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▌                 | 2011/2590 [42:17<17:22,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▌                 | 2012/2590 [42:19<18:53,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▌                 | 2013/2590 [42:21<17:54,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▋                 | 2014/2590 [42:23<18:00,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▋                 | 2015/2590 [42:25<17:23,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 78%|████████████████████████████████████████████████████████████▋                 | 2016/2590 [42:26<16:54,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▋                 | 2017/2590 [42:28<18:15,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▊                 | 2018/2590 [42:30<17:32,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▊                 | 2019/2590 [42:32<17:29,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▊                 | 2020/2590 [42:34<17:36,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▊                 | 2021/2590 [42:36<18:47,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▉                 | 2022/2590 [42:38<18:37,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▉                 | 2023/2590 [42:40<17:19,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▉                 | 2024/2590 [42:41<16:46,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|████████████████████████████████████████████████████████████▉                 | 2025/2590 [42:44<19:14,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████                 | 2026/2590 [42:46<19:21,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████                 | 2027/2590 [42:48<19:17,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████                 | 2028/2590 [42:50<17:33,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████                 | 2029/2590 [42:51<17:14,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████▏                | 2030/2590 [42:53<18:01,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████▏                | 2031/2590 [42:55<17:14,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████▏                | 2032/2590 [42:57<16:30,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 78%|█████████████████████████████████████████████████████████████▏                | 2033/2590 [42:58<15:49,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▎                | 2034/2590 [43:00<16:06,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▎                | 2035/2590 [43:02<17:39,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▎                | 2036/2590 [43:04<17:05,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▎                | 2037/2590 [43:06<17:07,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▍                | 2038/2590 [43:08<18:28,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▍                | 2039/2590 [43:10<18:17,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 79%|█████████████████████████████████████████████████████████████▍                | 2040/2590 [43:12<17:30,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▍                | 2041/2590 [43:14<16:51,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▍                | 2042/2590 [43:16<17:06,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▌                | 2043/2590 [43:18<18:31,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▌                | 2044/2590 [43:20<17:57,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▌                | 2045/2590 [43:22<17:45,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▌                | 2046/2590 [43:24<19:11,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▋                | 2047/2590 [43:26<17:48,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▋                | 2048/2590 [43:28<17:26,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▋                | 2049/2590 [43:29<16:52,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▋                | 2050/2590 [43:31<16:55,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▊                | 2051/2590 [43:34<19:06,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▊                | 2052/2590 [43:36<17:44,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▊                | 2053/2590 [43:38<17:37,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▊                | 2054/2590 [43:39<16:40,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▉                | 2055/2590 [43:42<18:28,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▉                | 2056/2590 [43:44<17:51,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▉                | 2057/2590 [43:45<17:03,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|█████████████████████████████████████████████████████████████▉                | 2058/2590 [43:47<16:37,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 79%|██████████████████████████████████████████████████████████████                | 2059/2590 [43:49<16:26,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████                | 2060/2590 [43:51<16:04,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████                | 2061/2590 [43:53<17:42,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████                | 2062/2590 [43:55<18:05,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▏               | 2063/2590 [43:58<18:28,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 80%|██████████████████████████████████████████████████████████████▏               | 2064/2590 [44:00<18:21,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▏               | 2065/2590 [44:01<17:29,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▏               | 2066/2590 [44:04<19:03,  2.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▏               | 2067/2590 [44:06<17:44,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▎               | 2068/2590 [44:07<16:55,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▎               | 2069/2590 [44:09<16:45,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▎               | 2070/2590 [44:11<16:43,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▎               | 2071/2590 [44:14<17:40,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▍               | 2072/2590 [44:15<16:49,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▍               | 2073/2590 [44:17<16:01,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▍               | 2074/2590 [44:19<15:34,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▍               | 2075/2590 [44:21<15:46,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▌               | 2076/2590 [44:23<17:45,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▌               | 2077/2590 [44:24<15:49,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▌               | 2078/2590 [44:26<15:46,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▌               | 2079/2590 [44:28<15:27,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▋               | 2080/2590 [44:30<15:43,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▋               | 2081/2590 [44:32<15:38,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▋               | 2082/2590 [44:34<16:38,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▋               | 2083/2590 [44:36<16:28,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 80%|██████████████████████████████████████████████████████████████▊               | 2084/2590 [44:38<16:20,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▊               | 2085/2590 [44:40<15:45,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▊               | 2086/2590 [44:41<15:27,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▊               | 2087/2590 [44:44<17:01,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 81%|██████████████████████████████████████████████████████████████▉               | 2088/2590 [44:46<16:04,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▉               | 2089/2590 [44:47<16:02,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▉               | 2090/2590 [44:49<15:36,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|██████████████████████████████████████████████████████████████▉               | 2091/2590 [44:51<15:36,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████               | 2092/2590 [44:54<17:26,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████               | 2093/2590 [44:55<16:30,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████               | 2094/2590 [44:57<15:52,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████               | 2095/2590 [44:59<15:36,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████               | 2096/2590 [45:01<16:45,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▏              | 2097/2590 [45:03<16:08,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▏              | 2098/2590 [45:05<16:52,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▏              | 2099/2590 [45:08<17:12,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▏              | 2100/2590 [45:10<16:40,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▎              | 2101/2590 [45:11<15:49,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▎              | 2102/2590 [45:14<16:53,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▎              | 2103/2590 [45:16<16:18,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▎              | 2104/2590 [45:17<16:03,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▍              | 2105/2590 [45:19<15:29,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▍              | 2106/2590 [45:22<17:06,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▍              | 2107/2590 [45:24<16:18,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▍              | 2108/2590 [45:26<16:20,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▌              | 2109/2590 [45:28<16:00,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 81%|███████████████████████████████████████████████████████████████▌              | 2110/2590 [45:30<17:03,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▌              | 2111/2590 [45:32<16:42,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 82%|███████████████████████████████████████████████████████████████▌              | 2112/2590 [45:34<16:06,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▋              | 2113/2590 [45:36<15:32,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▋              | 2114/2590 [45:38<16:39,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▋              | 2115/2590 [45:40<15:58,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▋              | 2116/2590 [45:42<16:06,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▊              | 2117/2590 [45:44<15:42,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▊              | 2118/2590 [45:47<17:12,  2.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▊              | 2119/2590 [45:48<16:33,  2.11s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▊              | 2120/2590 [45:50<15:27,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▉              | 2121/2590 [45:52<15:26,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▉              | 2122/2590 [45:55<16:36,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▉              | 2123/2590 [45:56<15:45,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▉              | 2124/2590 [45:58<15:53,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|███████████████████████████████████████████████████████████████▉              | 2125/2590 [46:01<17:05,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████              | 2126/2590 [46:03<16:26,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████              | 2127/2590 [46:05<15:50,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████              | 2128/2590 [46:07<15:14,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████              | 2129/2590 [46:09<15:11,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▏             | 2130/2590 [46:11<16:20,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▏             | 2131/2590 [46:13<16:04,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▏             | 2132/2590 [46:16<17:02,  2.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▏             | 2133/2590 [46:18<16:37,  2.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▎             | 2134/2590 [46:20<16:07,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 82%|████████████████████████████████████████████████████████████████▎             | 2135/2590 [46:22<16:45,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 82%|████████████████████████████████████████████████████████████████▎             | 2136/2590 [46:24<15:51,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▎             | 2137/2590 [46:26<15:47,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▍             | 2138/2590 [46:28<15:19,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▍             | 2139/2590 [46:31<16:37,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▍             | 2140/2590 [46:32<15:45,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▍             | 2141/2590 [46:34<15:06,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▌             | 2142/2590 [46:36<15:12,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▌             | 2143/2590 [46:38<14:42,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▌             | 2144/2590 [46:41<16:13,  2.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▌             | 2145/2590 [46:43<15:31,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▋             | 2146/2590 [46:44<14:38,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▋             | 2147/2590 [46:47<16:41,  2.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▋             | 2148/2590 [46:49<15:44,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▋             | 2149/2590 [46:51<15:08,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▋             | 2150/2590 [46:53<15:05,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▊             | 2151/2590 [46:56<16:08,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▊             | 2152/2590 [46:58<15:46,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▊             | 2153/2590 [47:00<15:04,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▊             | 2154/2590 [47:02<14:40,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▉             | 2155/2590 [47:04<16:12,  2.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▉             | 2156/2590 [47:06<14:57,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▉             | 2157/2590 [47:08<14:00,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|████████████████████████████████████████████████████████████████▉             | 2158/2590 [47:10<14:07,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|█████████████████████████████████████████████████████████████████             | 2159/2590 [47:12<15:03,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 83%|█████████████████████████████████████████████████████████████████             | 2160/2590 [47:14<14:56,  2.09s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|█████████████████████████████████████████████████████████████████             | 2161/2590 [47:16<14:37,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 83%|█████████████████████████████████████████████████████████████████             | 2162/2590 [47:18<15:14,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▏            | 2163/2590 [47:23<19:55,  2.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▏            | 2164/2590 [47:26<21:53,  3.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▏            | 2165/2590 [47:29<21:07,  2.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▏            | 2166/2590 [47:32<20:23,  2.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▎            | 2167/2590 [47:36<22:14,  3.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▎            | 2168/2590 [47:38<19:37,  2.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▎            | 2169/2590 [47:39<17:03,  2.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▎            | 2170/2590 [47:41<16:17,  2.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▍            | 2171/2590 [47:44<16:51,  2.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▍            | 2172/2590 [47:46<15:47,  2.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▍            | 2173/2590 [47:48<15:21,  2.21s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▍            | 2174/2590 [47:50<14:44,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▌            | 2175/2590 [47:53<15:59,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▌            | 2176/2590 [47:54<14:54,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▌            | 2177/2590 [47:56<14:18,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▌            | 2178/2590 [47:58<14:24,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▌            | 2179/2590 [48:01<15:28,  2.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▋            | 2180/2590 [48:03<15:02,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▋            | 2181/2590 [48:05<14:16,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▋            | 2182/2590 [48:07<13:43,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▋            | 2183/2590 [48:09<13:39,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 84%|█████████████████████████████████████████████████████████████████▊            | 2184/2590 [48:11<14:38,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▊            | 2185/2590 [48:13<14:21,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▊            | 2186/2590 [48:15<13:57,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▊            | 2187/2590 [48:17<13:30,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 84%|█████████████████████████████████████████████████████████████████▉            | 2188/2590 [48:19<13:16,  1.98s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|█████████████████████████████████████████████████████████████████▉            | 2189/2590 [48:22<14:24,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|█████████████████████████████████████████████████████████████████▉            | 2190/2590 [48:23<13:36,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|█████████████████████████████████████████████████████████████████▉            | 2191/2590 [48:25<13:35,  2.05s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████            | 2192/2590 [48:28<14:12,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████            | 2193/2590 [48:31<15:14,  2.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████            | 2194/2590 [48:33<15:47,  2.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████            | 2195/2590 [48:35<15:10,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▏           | 2196/2590 [48:37<14:23,  2.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▏           | 2197/2590 [48:39<13:57,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▏           | 2198/2590 [48:42<15:08,  2.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▏           | 2199/2590 [48:44<14:29,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▎           | 2200/2590 [48:46<14:25,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▎           | 2201/2590 [48:48<14:05,  2.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▎           | 2202/2590 [48:51<14:45,  2.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▎           | 2203/2590 [48:53<14:17,  2.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▍           | 2204/2590 [48:55<13:37,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▍           | 2205/2590 [48:57<13:36,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▍           | 2206/2590 [48:59<14:25,  2.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▍           | 2207/2590 [49:01<13:46,  2.16s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 85%|██████████████████████████████████████████████████████████████████▍           | 2208/2590 [49:03<13:39,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▌           | 2209/2590 [49:06<15:17,  2.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▌           | 2210/2590 [49:10<17:32,  2.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▌           | 2211/2590 [49:13<17:12,  2.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▌           | 2212/2590 [49:15<15:47,  2.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▋           | 2213/2590 [49:17<14:35,  2.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 85%|██████████████████████████████████████████████████████████████████▋           | 2214/2590 [49:19<15:16,  2.44s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▋           | 2215/2590 [49:21<14:22,  2.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▋           | 2216/2590 [49:25<16:43,  2.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▊           | 2217/2590 [49:27<15:31,  2.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▊           | 2218/2590 [49:32<20:27,  3.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▊           | 2219/2590 [49:34<18:34,  3.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▊           | 2220/2590 [49:36<16:03,  2.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▉           | 2221/2590 [49:37<13:10,  2.14s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▉           | 2222/2590 [49:38<11:01,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▉           | 2223/2590 [49:40<11:04,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|██████████████████████████████████████████████████████████████████▉           | 2224/2590 [49:41<09:58,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████           | 2225/2590 [49:42<08:59,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████           | 2226/2590 [49:43<08:14,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████           | 2227/2590 [49:44<07:45,  1.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████           | 2228/2590 [49:46<08:25,  1.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▏          | 2229/2590 [49:47<07:50,  1.30s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▏          | 2230/2590 [49:48<07:36,  1.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▏          | 2231/2590 [49:49<07:17,  1.22s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 86%|███████████████████████████████████████████████████████████████████▏          | 2232/2590 [49:51<07:05,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▏          | 2233/2590 [49:52<07:48,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▎          | 2234/2590 [49:53<07:26,  1.25s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▎          | 2235/2590 [49:54<07:02,  1.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▎          | 2236/2590 [49:55<06:48,  1.15s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▎          | 2237/2590 [49:57<06:52,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▍          | 2238/2590 [49:58<07:22,  1.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▍          | 2239/2590 [49:59<07:00,  1.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 86%|███████████████████████████████████████████████████████████████████▍          | 2240/2590 [50:00<06:49,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▍          | 2241/2590 [50:01<06:49,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▌          | 2242/2590 [50:03<06:47,  1.17s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▌          | 2243/2590 [50:04<07:50,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▌          | 2244/2590 [50:06<07:42,  1.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▌          | 2245/2590 [50:07<07:49,  1.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▋          | 2246/2590 [50:08<07:41,  1.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▋          | 2247/2590 [50:10<08:38,  1.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▋          | 2248/2590 [50:12<08:34,  1.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▋          | 2249/2590 [50:13<08:24,  1.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▊          | 2250/2590 [50:14<07:52,  1.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▊          | 2251/2590 [50:16<08:10,  1.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▊          | 2252/2590 [50:17<07:36,  1.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▊          | 2253/2590 [50:18<07:20,  1.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▉          | 2254/2590 [50:20<08:48,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▉          | 2255/2590 [50:30<21:29,  3.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 87%|███████████████████████████████████████████████████████████████████▉          | 2256/2590 [50:33<20:05,  3.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|███████████████████████████████████████████████████████████████████▉          | 2257/2590 [50:36<19:36,  3.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████          | 2258/2590 [50:39<18:30,  3.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████          | 2259/2590 [50:43<19:14,  3.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████          | 2260/2590 [50:45<17:30,  3.18s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████          | 2261/2590 [50:48<16:12,  2.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████          | 2262/2590 [50:50<14:46,  2.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████▏         | 2263/2590 [50:53<14:58,  2.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████▏         | 2264/2590 [50:56<15:37,  2.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████▏         | 2265/2590 [50:59<15:14,  2.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 87%|████████████████████████████████████████████████████████████████████▏         | 2266/2590 [51:01<14:18,  2.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▎         | 2267/2590 [51:03<13:39,  2.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▎         | 2268/2590 [51:06<14:01,  2.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▎         | 2269/2590 [51:08<13:43,  2.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▎         | 2270/2590 [51:10<12:52,  2.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▍         | 2271/2590 [51:12<12:22,  2.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▍         | 2272/2590 [51:16<14:22,  2.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▍         | 2273/2590 [51:19<14:53,  2.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▍         | 2274/2590 [51:22<14:08,  2.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▌         | 2275/2590 [51:24<14:11,  2.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▌         | 2276/2590 [51:27<13:32,  2.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▌         | 2277/2590 [51:28<11:52,  2.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▌         | 2278/2590 [51:30<10:48,  2.08s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▋         | 2279/2590 [51:32<10:21,  2.00s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 88%|████████████████████████████████████████████████████████████████████▋         | 2280/2590 [51:34<10:40,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▋         | 2281/2590 [51:35<09:59,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▋         | 2282/2590 [51:37<09:23,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▊         | 2283/2590 [51:39<08:53,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▊         | 2284/2590 [51:41<09:41,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▊         | 2285/2590 [51:42<09:04,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▊         | 2286/2590 [51:44<08:38,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▊         | 2287/2590 [51:46<09:25,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▉         | 2288/2590 [51:49<10:42,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▉         | 2289/2590 [51:50<09:44,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▉         | 2290/2590 [51:52<09:21,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|████████████████████████████████████████████████████████████████████▉         | 2291/2590 [51:54<09:06,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 88%|█████████████████████████████████████████████████████████████████████         | 2292/2590 [51:55<08:32,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████         | 2293/2590 [51:57<09:12,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████         | 2294/2590 [51:59<08:32,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████         | 2295/2590 [52:00<08:10,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▏        | 2296/2590 [52:02<08:23,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▏        | 2297/2590 [52:04<09:01,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▏        | 2298/2590 [52:06<08:29,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▏        | 2299/2590 [52:08<08:31,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▎        | 2300/2590 [52:09<08:30,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▎        | 2301/2590 [52:12<09:18,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▎        | 2302/2590 [52:13<09:00,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▎        | 2303/2590 [52:15<08:17,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 89%|█████████████████████████████████████████████████████████████████████▍        | 2304/2590 [52:16<07:58,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▍        | 2305/2590 [52:18<07:16,  1.53s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▍        | 2306/2590 [52:20<08:15,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▍        | 2307/2590 [52:22<08:06,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▌        | 2308/2590 [52:23<07:43,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▌        | 2309/2590 [52:25<07:33,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▌        | 2310/2590 [52:27<08:30,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▌        | 2311/2590 [52:28<08:02,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▋        | 2312/2590 [52:30<08:05,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▋        | 2313/2590 [52:32<07:56,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▋        | 2314/2590 [52:33<07:29,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▋        | 2315/2590 [52:36<08:22,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▋        | 2316/2590 [52:37<07:59,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▊        | 2317/2590 [52:39<07:35,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 89%|█████████████████████████████████████████████████████████████████████▊        | 2318/2590 [52:40<07:34,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▊        | 2319/2590 [52:42<07:23,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▊        | 2320/2590 [52:43<07:21,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▉        | 2321/2590 [52:46<08:08,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▉        | 2322/2590 [52:47<07:39,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▉        | 2323/2590 [52:49<07:23,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|█████████████████████████████████████████████████████████████████████▉        | 2324/2590 [52:51<08:11,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████        | 2325/2590 [52:53<08:35,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████        | 2326/2590 [52:56<09:18,  2.12s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████        | 2327/2590 [52:57<08:26,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 90%|██████████████████████████████████████████████████████████████████████        | 2328/2590 [52:58<07:33,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▏       | 2329/2590 [53:00<07:15,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▏       | 2330/2590 [53:02<07:16,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▏       | 2331/2590 [53:04<07:51,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▏       | 2332/2590 [53:05<07:27,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▎       | 2333/2590 [53:07<07:19,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▎       | 2334/2590 [53:08<06:59,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▎       | 2335/2590 [53:10<06:51,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▎       | 2336/2590 [53:12<07:47,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▍       | 2337/2590 [53:14<07:09,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▍       | 2338/2590 [53:15<06:57,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▍       | 2339/2590 [53:17<06:50,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▍       | 2340/2590 [53:18<06:36,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▌       | 2341/2590 [53:21<07:18,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▌       | 2342/2590 [53:22<07:06,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 90%|██████████████████████████████████████████████████████████████████████▌       | 2343/2590 [53:24<06:48,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▌       | 2344/2590 [53:25<06:39,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▌       | 2345/2590 [53:28<07:35,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▋       | 2346/2590 [53:29<07:16,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▋       | 2347/2590 [53:31<07:14,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▋       | 2348/2590 [53:33<07:13,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▋       | 2349/2590 [53:35<07:44,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▊       | 2350/2590 [53:37<07:13,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▊       | 2351/2590 [53:38<07:03,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 91%|██████████████████████████████████████████████████████████████████████▊       | 2352/2590 [53:39<06:10,  1.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▊       | 2353/2590 [53:41<06:09,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▉       | 2354/2590 [53:43<06:11,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▉       | 2355/2590 [53:45<07:03,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▉       | 2356/2590 [53:46<06:38,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|██████████████████████████████████████████████████████████████████████▉       | 2357/2590 [53:48<06:22,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████       | 2358/2590 [53:50<06:24,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████       | 2359/2590 [53:51<06:18,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████       | 2360/2590 [53:53<07:02,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████       | 2361/2590 [53:55<07:07,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▏      | 2362/2590 [53:57<07:08,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▏      | 2363/2590 [53:59<07:04,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▏      | 2364/2590 [54:01<06:45,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▏      | 2365/2590 [54:03<07:10,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▎      | 2366/2590 [54:04<06:40,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▎      | 2367/2590 [54:06<06:30,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▎      | 2368/2590 [54:07<06:07,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 91%|███████████████████████████████████████████████████████████████████████▎      | 2369/2590 [54:09<05:57,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▎      | 2370/2590 [54:11<06:35,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▍      | 2371/2590 [54:13<06:03,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▍      | 2372/2590 [54:14<06:02,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▍      | 2373/2590 [54:16<06:09,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▍      | 2374/2590 [54:18<06:42,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▌      | 2375/2590 [54:20<06:17,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 92%|███████████████████████████████████████████████████████████████████████▌      | 2376/2590 [54:21<06:11,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▌      | 2377/2590 [54:23<05:51,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▌      | 2378/2590 [54:25<05:52,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▋      | 2379/2590 [54:27<06:44,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▋      | 2380/2590 [54:29<06:37,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▋      | 2381/2590 [54:31<06:32,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▋      | 2382/2590 [54:33<06:34,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▊      | 2383/2590 [54:35<07:00,  2.03s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▊      | 2384/2590 [54:37<06:30,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▊      | 2385/2590 [54:38<06:07,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▊      | 2386/2590 [54:40<05:49,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▉      | 2387/2590 [54:41<05:42,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▉      | 2388/2590 [54:44<06:11,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▉      | 2389/2590 [54:45<05:47,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|███████████████████████████████████████████████████████████████████████▉      | 2390/2590 [54:47<05:30,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|████████████████████████████████████████████████████████████████████████      | 2391/2590 [54:48<05:31,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|████████████████████████████████████████████████████████████████████████      | 2392/2590 [54:50<05:18,  1.61s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|████████████████████████████████████████████████████████████████████████      | 2393/2590 [54:52<05:49,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|████████████████████████████████████████████████████████████████████████      | 2394/2590 [54:54<05:45,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 92%|████████████████████████████████████████████████████████████████████████▏     | 2395/2590 [54:55<05:32,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▏     | 2396/2590 [54:56<05:03,  1.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▏     | 2397/2590 [54:59<05:39,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▏     | 2398/2590 [55:00<05:20,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▏     | 2399/2590 [55:02<05:21,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 93%|████████████████████████████████████████████████████████████████████████▎     | 2400/2590 [55:04<06:14,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▎     | 2401/2590 [55:06<06:16,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▎     | 2402/2590 [55:09<06:28,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▎     | 2403/2590 [55:10<05:59,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▍     | 2404/2590 [55:12<05:40,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▍     | 2405/2590 [55:13<05:21,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▍     | 2406/2590 [55:16<05:51,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▍     | 2407/2590 [55:17<05:28,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▌     | 2408/2590 [55:19<05:18,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▌     | 2409/2590 [55:21<05:12,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▌     | 2410/2590 [55:22<05:03,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▌     | 2411/2590 [55:24<05:25,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▋     | 2412/2590 [55:26<05:42,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▋     | 2413/2590 [55:28<05:26,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▋     | 2414/2590 [55:30<05:20,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▋     | 2415/2590 [55:33<06:00,  2.06s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▊     | 2416/2590 [55:34<05:37,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▊     | 2417/2590 [55:36<05:30,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▊     | 2418/2590 [55:38<05:13,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▊     | 2419/2590 [55:40<05:28,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▉     | 2420/2590 [55:41<05:14,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 93%|████████████████████████████████████████████████████████████████████████▉     | 2421/2590 [55:43<04:54,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|████████████████████████████████████████████████████████████████████████▉     | 2422/2590 [55:44<04:41,  1.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|████████████████████████████████████████████████████████████████████████▉     | 2423/2590 [55:46<04:30,  1.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 94%|█████████████████████████████████████████████████████████████████████████     | 2424/2590 [55:48<04:59,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████     | 2425/2590 [55:50<04:43,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████     | 2426/2590 [55:53<05:48,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████     | 2427/2590 [55:55<06:02,  2.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████     | 2428/2590 [56:03<10:39,  3.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▏    | 2429/2590 [56:09<12:07,  4.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▏    | 2430/2590 [56:12<10:45,  4.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▏    | 2431/2590 [56:14<08:49,  3.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▏    | 2432/2590 [56:16<07:47,  2.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▎    | 2433/2590 [56:18<07:14,  2.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▎    | 2434/2590 [56:20<06:37,  2.55s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▎    | 2435/2590 [56:23<06:56,  2.68s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▎    | 2436/2590 [56:25<06:25,  2.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▍    | 2437/2590 [56:28<06:21,  2.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▍    | 2438/2590 [56:30<06:08,  2.43s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▍    | 2439/2590 [56:32<06:00,  2.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▍    | 2440/2590 [56:34<05:50,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▌    | 2441/2590 [56:37<06:09,  2.48s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▌    | 2442/2590 [56:39<05:54,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▌    | 2443/2590 [56:42<05:41,  2.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▌    | 2444/2590 [56:44<05:44,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▋    | 2445/2590 [56:46<05:27,  2.26s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▋    | 2446/2590 [56:48<05:16,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 94%|█████████████████████████████████████████████████████████████████████████▋    | 2447/2590 [56:51<05:53,  2.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 95%|█████████████████████████████████████████████████████████████████████████▋    | 2448/2590 [56:53<05:31,  2.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▊    | 2449/2590 [56:56<05:29,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▊    | 2450/2590 [56:58<05:20,  2.29s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▊    | 2451/2590 [57:01<06:01,  2.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▊    | 2452/2590 [57:03<05:37,  2.45s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▊    | 2453/2590 [57:05<05:21,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▉    | 2454/2590 [57:08<05:21,  2.36s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▉    | 2455/2590 [57:10<05:06,  2.27s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▉    | 2456/2590 [57:13<05:40,  2.54s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|█████████████████████████████████████████████████████████████████████████▉    | 2457/2590 [57:15<05:27,  2.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████    | 2458/2590 [57:18<05:47,  2.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████    | 2459/2590 [57:20<05:14,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████    | 2460/2590 [57:23<05:11,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████    | 2461/2590 [57:25<04:53,  2.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▏   | 2462/2590 [57:26<04:39,  2.19s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▏   | 2463/2590 [57:30<05:12,  2.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▏   | 2464/2590 [57:32<05:02,  2.40s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▏   | 2465/2590 [57:34<05:01,  2.41s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▎   | 2466/2590 [57:36<04:42,  2.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▎   | 2467/2590 [57:38<04:30,  2.20s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▎   | 2468/2590 [57:41<05:01,  2.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▎   | 2469/2590 [57:43<04:39,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▍   | 2470/2590 [57:46<04:41,  2.34s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▍   | 2471/2590 [57:48<04:27,  2.24s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 95%|██████████████████████████████████████████████████████████████████████████▍   | 2472/2590 [57:51<05:06,  2.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 95%|██████████████████████████████████████████████████████████████████████████▍   | 2473/2590 [57:54<05:20,  2.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▌   | 2474/2590 [57:57<05:19,  2.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▌   | 2475/2590 [57:59<04:55,  2.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▌   | 2476/2590 [58:01<04:44,  2.49s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▌   | 2477/2590 [58:05<05:01,  2.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▋   | 2478/2590 [58:07<04:46,  2.56s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▋   | 2479/2590 [58:09<04:29,  2.42s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▋   | 2480/2590 [58:11<04:14,  2.31s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▋   | 2481/2590 [58:13<04:13,  2.32s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▋   | 2482/2590 [58:16<04:29,  2.50s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▊   | 2483/2590 [58:18<04:15,  2.38s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▊   | 2484/2590 [58:21<04:07,  2.33s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▊   | 2485/2590 [58:23<04:18,  2.47s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▊   | 2486/2590 [58:27<04:37,  2.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▉   | 2487/2590 [58:29<04:29,  2.62s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▉   | 2488/2590 [58:31<04:17,  2.52s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▉   | 2489/2590 [58:33<04:00,  2.38s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|██████████████████████████████████████████████████████████████████████████▉   | 2490/2590 [58:36<03:58,  2.39s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████   | 2491/2590 [58:39<04:16,  2.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████   | 2492/2590 [58:41<04:06,  2.51s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████   | 2493/2590 [58:43<03:50,  2.38s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████   | 2494/2590 [58:46<03:45,  2.35s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████▏  | 2495/2590 [58:48<03:36,  2.28s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 96%|███████████████████████████████████████████████████████████████████████████▏  | 2496/2590 [58:51<03:51,  2.46s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████▏  | 2497/2590 [58:52<03:27,  2.23s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████▏  | 2498/2590 [58:54<03:07,  2.04s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 96%|███████████████████████████████████████████████████████████████████████████▎  | 2499/2590 [58:56<02:58,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▎  | 2500/2590 [58:57<02:47,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▎  | 2501/2590 [59:00<02:59,  2.01s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▎  | 2502/2590 [59:01<02:52,  1.97s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▍  | 2503/2590 [59:03<02:41,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▍  | 2504/2590 [59:05<02:33,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▍  | 2505/2590 [59:06<02:31,  1.78s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▍  | 2506/2590 [59:09<02:41,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▌  | 2507/2590 [59:10<02:36,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▌  | 2508/2590 [59:13<02:40,  1.95s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▌  | 2509/2590 [59:14<02:31,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▌  | 2510/2590 [59:16<02:20,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▌  | 2511/2590 [59:18<02:32,  1.93s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▋  | 2512/2590 [59:20<02:21,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▋  | 2513/2590 [59:21<02:14,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▋  | 2514/2590 [59:23<02:11,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▋  | 2515/2590 [59:25<02:07,  1.70s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▊  | 2516/2590 [59:27<02:29,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▊  | 2517/2590 [59:30<02:32,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▊  | 2518/2590 [59:32<02:29,  2.07s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▊  | 2519/2590 [59:34<02:23,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 97%|███████████████████████████████████████████████████████████████████████████▉  | 2520/2590 [59:35<02:14,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▉  | 2521/2590 [59:37<02:19,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▉  | 2522/2590 [59:39<02:13,  1.96s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|███████████████████████████████████████████████████████████████████████████▉  | 2523/2590 [59:41<02:06,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|████████████████████████████████████████████████████████████████████████████  | 2524/2590 [59:42<01:56,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 97%|████████████████████████████████████████████████████████████████████████████  | 2525/2590 [59:45<02:11,  2.02s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████  | 2526/2590 [59:47<02:02,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████  | 2527/2590 [59:49<02:00,  1.91s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▏ | 2528/2590 [59:50<01:54,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▏ | 2529/2590 [59:52<01:47,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▏ | 2530/2590 [59:54<01:44,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▏ | 2531/2590 [59:56<01:48,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▎ | 2532/2590 [59:57<01:39,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|████████████████████████████████████████████████████████████████████████████▎ | 2533/2590 [59:58<01:29,  1.57s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▎ | 2534/2590 [1:00:00<01:29,  1.60s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▍ | 2535/2590 [1:00:02<01:27,  1.59s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▍ | 2536/2590 [1:00:03<01:25,  1.58s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▍ | 2537/2590 [1:00:06<01:37,  1.84s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▍ | 2538/2590 [1:00:07<01:31,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▌ | 2539/2590 [1:00:09<01:26,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▌ | 2540/2590 [1:00:10<01:21,  1.64s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▌ | 2541/2590 [1:00:12<01:20,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▌ | 2542/2590 [1:00:14<01:19,  1.65s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▌ | 2543/2590 [1:00:16<01:27,  1.87s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 98%|██████████████████████████████████████████████████████████████████████████▋ | 2544/2590 [1:00:18<01:22,  1.79s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▋ | 2545/2590 [1:00:19<01:17,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▋ | 2546/2590 [1:00:21<01:13,  1.67s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▋ | 2547/2590 [1:00:22<01:11,  1.66s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▊ | 2548/2590 [1:00:24<01:08,  1.63s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▊ | 2549/2590 [1:00:26<01:13,  1.80s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▊ | 2550/2590 [1:00:28<01:10,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 98%|██████████████████████████████████████████████████████████████████████████▊ | 2551/2590 [1:00:29<01:07,  1.73s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|██████████████████████████████████████████████████████████████████████████▉ | 2552/2590 [1:00:31<01:05,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|██████████████████████████████████████████████████████████████████████████▉ | 2553/2590 [1:00:33<01:06,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|██████████████████████████████████████████████████████████████████████████▉ | 2554/2590 [1:00:36<01:16,  2.13s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|██████████████████████████████████████████████████████████████████████████▉ | 2555/2590 [1:00:38<01:13,  2.10s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████ | 2556/2590 [1:00:39<01:04,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████ | 2557/2590 [1:00:41<00:59,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████ | 2558/2590 [1:00:43<00:58,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████ | 2559/2590 [1:00:45<01:01,  1.99s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████ | 2560/2590 [1:00:47<00:56,  1.90s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▏| 2561/2590 [1:00:49<00:54,  1.88s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▏| 2562/2590 [1:00:50<00:50,  1.81s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▏| 2563/2590 [1:00:52<00:47,  1.74s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▏| 2564/2590 [1:00:54<00:50,  1.94s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▎| 2565/2590 [1:00:56<00:46,  1.85s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▎| 2566/2590 [1:00:58<00:42,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▎| 2567/2590 [1:00:59<00:40,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)

 99%|███████████████████████████████████████████████████████████████████████████▎| 2568/2590 [1:01:01<00:37,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▍| 2569/2590 [1:01:03<00:39,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▍| 2570/2590 [1:01:05<00:37,  1.86s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▍| 2571/2590 [1:01:07<00:33,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▍| 2572/2590 [1:01:08<00:31,  1.72s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▌| 2573/2590 [1:01:10<00:29,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▌| 2574/2590 [1:01:12<00:30,  1.92s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▌| 2575/2590 [1:01:14<00:27,  1.82s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▌| 2576/2590 [1:01:16<00:25,  1.83s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
 99%|███████████████████████████████████████████████████████████████████████████▌| 2577/2590 [1:01:17<00:22,  1.77s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▋| 2578/2590 [1:01:19<00:20,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▋| 2579/2590 [1:01:21<00:18,  1.71s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▋| 2580/2590 [1:01:23<00:18,  1.89s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▋| 2581/2590 [1:01:24<00:15,  1.76s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▊| 2582/2590 [1:01:26<00:14,  1.75s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▊| 2583/2590 [1:01:28<00:11,  1.69s/it]C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2042649833.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(df)
100%|███████████████████████████████████████████████████████████████████████████▊| 2584/2590 [1:01:29<00:08,  1.43s/it]

ReaderError: unacceptable character #x0000: special characters are not allowed
  in "Documents\desktop.ini", position 3

In [5]:
backup = final_df.copy()

In [6]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,...,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.A Deshmukh,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,5.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,2.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,NaN,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,NaN,Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],male,T20,6.0,Pakistan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],male,T20,8.0,India,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],male,T20,NaN,Netherlands,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],male,T20,4.0,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [8]:
final_df

,innings,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.players.Australia,info.players.Sri Lanka,...,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.A Deshmukh,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],male,T20,Sri Lanka,20,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],male,T20,Sri Lanka,20,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],male,T20,Australia,20,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],male,T20,Hong Kong,20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],male,T20,Zimbabwe,20,[E Chigumbura],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-03-04],male,T20,Pakistan,20,[Umar Akmal],NaN,"[LD Chandimal, TM Dilshan, GSNFG Jayasuriya, C...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,[2016-03-06],male,T20,India,20,[S Dhawan],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,[2016-02-03],male,T20,Netherlands,20,[Mudassar Bukhari],NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2016-09-06],male,T20,Australia,20,[GJ Maxwell],"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-09-09],male,T20,Australia,20,[GJ Maxwell],"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
final_df['info.gender'].value_counts()

male    2584
Name: info.gender, dtype: int64

In [10]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

,innings,info.balls_per_over,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.players.Australia,info.players.Sri Lanka,info.registry.people.A Zampa,...,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.A Deshmukh,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],T20,Sri Lanka,20,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],T20,Sri Lanka,20,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],T20,Australia,20,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],T20,Hong Kong,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],T20,Zimbabwe,20,[E Chigumbura],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-03-04],T20,Pakistan,20,[Umar Akmal],NaN,"[LD Chandimal, TM Dilshan, GSNFG Jayasuriya, C...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,[2016-03-06],T20,India,20,[S Dhawan],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,[2016-02-03],T20,Netherlands,20,[Mudassar Bukhari],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2016-09-06],T20,Australia,20,[GJ Maxwell],"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-09-09],T20,Australia,20,[GJ Maxwell],"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
final_df['info.match_type'].value_counts()

T20    2584
Name: info.match_type, dtype: int64

In [12]:
final_df['info.overs'].value_counts()

20    2581
50       3
Name: info.overs, dtype: int64

In [13]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3157072726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,info.balls_per_over,info.dates,info.outcome.winner,info.player_of_match,info.players.Australia,info.players.Sri Lanka,info.registry.people.A Zampa,info.registry.people.AJ Finch,info.registry.people.AJ Turner,...,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.A Deshmukh,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],Sri Lanka,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",14f96089,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],Sri Lanka,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",NaN,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],Australia,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",14f96089,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],Zimbabwe,[E Chigumbura],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-03-04],Pakistan,[Umar Akmal],NaN,"[LD Chandimal, TM Dilshan, GSNFG Jayasuriya, C...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,[2016-03-06],India,[S Dhawan],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,[2016-02-03],Netherlands,[Mudassar Bukhari],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2016-09-06],Australia,[GJ Maxwell],"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-09-09],Australia,[GJ Maxwell],"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [15]:
matches = pickle.load(open('dataset_level1.pkl','rb'))
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.2: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {0.4: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {0.5: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {1.1: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.3: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.5: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.6: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {2.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.6: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.3: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.5: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.6: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.6: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.1: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'wides': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {5.3: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.7: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.4: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'byes': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {7.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {7.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {8.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.2: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.4: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'extras': {'legbyes': 1},
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {10.3: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'M Klinger'}}},
 {10.4: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {10.5: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.1: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {11.2: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.3: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'AJ Finch'}}},
 {11.4: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.5: {'batsman': 'MC Henriques',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.6: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.1: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.2: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.3: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.4: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.5: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.6: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.1: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.2: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'extras': {'wides': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {13.3: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.5: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.7: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.1: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.2: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.3: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.4: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.5: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.1: {'batsman': 'MC Henriques',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['CK Kapugedera'],
    'kind': 'caught',
    'player_out': 'MC Henriques'}}},
 {15.2: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.3: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.4: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.5: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.6: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'extras': {'wides': 1},
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.7: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {16.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {16.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.3: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.6: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.2: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.3: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'noballs': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.4: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.5: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.6: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.7: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.3: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'TM Head'}}},
 {18.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'JP Faulkner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'AJ Turner'}}},
 {18.6: {'batsman': 'JP Faulkner',
   'bowler': 'SL Malinga',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {19.2: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.3: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.4: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'wides': 1},
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {19.5: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1},
   'wicket': {'fielders': ['CK Kapugedera', 'KMDN Kulasekara'],
    'kind': 'run out',
    'player_out': 'TD Paine'}}},
 {19.6: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.7: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}}]

In [17]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)
C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3780558368.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  delivery_df = delivery_df.append(loop_df)

In [18]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...,...
121,2582,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium
122,2582,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium
123,2582,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium
124,2582,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium
125,2582,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium

In [19]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [20]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [21]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
121,2582,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
122,2582,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
123,2582,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
124,2582,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
125,2582,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [22]:
delivery_df.drop(columns=['teams'],inplace=True)

In [23]:
delivery_df['batting_team'].unique()

array(['Australia', 'Hong Kong', 'Zimbabwe', 'India', 'Bangladesh',
       'New Zealand', 'South Africa', 'England', 'West Indies',
       'Pakistan', 'Scotland', 'Oman', 'Ireland', 'Papua New Guinea',
       'United Arab Emirates', 'Sri Lanka', 'Netherlands', 'Nepal',
       'Vanuatu', 'Philippines', 'United States of America', 'Germany',
       'Ghana', 'Uganda', 'Kenya', 'Namibia', 'Nigeria', 'Botswana',
       'Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway', 'Thailand',
       'Malaysia', 'Maldives', 'Singapore', 'Kuwait', 'Bermuda', 'Canada',
       'Cayman Islands', 'Portugal', 'Gibraltar', 'Spain', 'Bhutan',
       'Qatar', 'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania',
       'Luxembourg', 'Austria', 'Czech Republic', 'Greece', 'Serbia',
       'Malta', 'France', 'Sweden', 'Rwanda', 'Finland', 'Hungary',
       'Estonia', 'Cyprus', 'Switzerland', 'Seychelles', 'Malawi',
       'Lesotho', 'Swaziland', 'Tanzania', 'Mozambique', 'Sierra Leone',
       'Cameroon', 'Bahrain', 'Belize', 'Bahamas', 'Argentina', 'Panama',
       'Israel', 'Croatia', 'Turkey', 'Slovenia', 'Cook Islands', 'Samoa',
       'Fiji', 'Japan', 'Indonesia', 'South Korea', 'Mali', 'St Helena',
       'Gambia', 'Eswatini', 'Saudi Arabia', 'China', 'Myanmar', 'Chile',
       'Mexico', 'Cambodia', 'Costa Rica', 'Mongolia', 'Brazil',
       'Ivory Coast', 'Suriname'], dtype=object)

In [24]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [25]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [26]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
121,2582,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
122,2582,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
123,2582,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
124,2582,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
125,2582,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [27]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [28]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
121,2582,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
122,2582,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
123,2582,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
124,2582,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
125,2582,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [29]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [30]:
output[output['city'].isnull()]['venue'].value_counts()

Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: venue, dtype: int64

In [31]:
x = np.where(output['city'].isnull(), output['venue'].str.split().apply(lambda x:x[0]), output['city'])

In [32]:
output['city'] = x

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2208188131.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output['city'] = x

In [33]:
output.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [34]:
output.drop(columns=['venue'],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2962604362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output.drop(columns=['venue'],inplace=True)

In [35]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,2582,Sri Lanka,Australia,19.3,1,0,Colombo
122,2582,Sri Lanka,Australia,19.4,0,0,Colombo
123,2582,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,2582,Sri Lanka,Australia,19.6,2,0,Colombo
125,2582,Sri Lanka,Australia,19.7,1,0,Colombo

In [36]:
total_df = output.groupby('match_id').sum()['runs'].reset_index()
output = output.merge(total_df,on='match_id')

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\3314073196.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  total_df = output.groupby('match_id').sum()['runs'].reset_index()

In [37]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,runs_y
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,168
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,168
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,168
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,168
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,168
...,...,...,...,...,...,...,...,...
98090,2582,Sri Lanka,Australia,19.3,1,0,Colombo,128
98091,2582,Sri Lanka,Australia,19.4,0,0,Colombo,128
98092,2582,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,128
98093,2582,Sri Lanka,Australia,19.6,2,0,Colombo,128
98094,2582,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [38]:
output['current_score'] = output.groupby('match_id').cumsum()['runs_x']

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\167387062.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  output['current_score'] = output.groupby('match_id').cumsum()['runs_x']

In [39]:
output['over'] = output['ball'].apply(lambda x:str(x).split(".")[0])
output['ball_no'] = output['ball'].apply(lambda x:str(x).split(".")[1])

In [40]:
output['balls_bowled'] = (output['over'].astype('int')*6) + output['ball_no'].astype('int')

In [41]:
output['crr'] = round((output['current_score']*6)/output['balls_bowled'],2)

In [42]:
output['player_dismissed'] = output['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
output['player_dismissed'] = output['player_dismissed'].astype('int')
output['player_dismissed'] = output.groupby('match_id').cumsum()['player_dismissed']
output['wickets_left'] = 10 - output['player_dismissed']

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\2957949265.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  output['player_dismissed'] = output.groupby('match_id').cumsum()['player_dismissed']

In [43]:
final_df = output[['match_id','batting_team','bowling_team','runs_x','current_score','balls_bowled','wickets_left','crr','city','runs_y']]

In [44]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y
0,2,Australia,Sri Lanka,0,0,1,10,0.00,Melbourne,168
1,2,Australia,Sri Lanka,0,0,2,10,0.00,Melbourne,168
2,2,Australia,Sri Lanka,1,1,3,10,2.00,Melbourne,168
3,2,Australia,Sri Lanka,2,3,4,10,4.50,Melbourne,168
4,2,Australia,Sri Lanka,0,3,5,10,3.60,Melbourne,168
...,...,...,...,...,...,...,...,...,...,...
98090,2582,Sri Lanka,Australia,1,125,117,2,6.41,Colombo,128
98091,2582,Sri Lanka,Australia,0,125,118,2,6.36,Colombo,128
98092,2582,Sri Lanka,Australia,0,125,119,1,6.30,Colombo,128
98093,2582,Sri Lanka,Australia,2,127,120,1,6.35,Colombo,128
98094,2582,Sri Lanka,Australia,1,128,121,1,6.35,Colombo,128

In [45]:
final_df = final_df.sample(final_df.shape[0])

In [46]:
final_df['balls_left'] = 120 - final_df['balls_bowled']
final_df['balls_left'] = final_df['balls_left'].apply(lambda x:0 if x<0 else x)

In [47]:
final_df['crr'] = round((final_df['current_score']*6)/final_df['balls_bowled'],2)

In [48]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y,balls_left
50264,1542,Bangladesh,Australia,0,32,34,9,5.65,North Sound,140,86
87943,2444,Sri Lanka,West Indies,0,5,4,10,7.50,Mirpur,160,116
72338,2259,Australia,England,0,2,8,10,1.50,Melbourne,147,112
65997,2198,India,New Zealand,0,95,85,5,6.71,Wellington,149,35
34429,711,Pakistan,West Indies,0,109,84,6,7.79,Karachi,172,36
...,...,...,...,...,...,...,...,...,...,...,...
39540,981,New Zealand,Bangladesh,2,64,45,9,8.53,Christchurch,208,75
74367,2279,Sri Lanka,Australia,2,84,68,8,7.41,Pallekele,198,52
86880,2433,Sri Lanka,England,1,94,74,9,7.62,Chittagong,189,46
91340,2475,Pakistan,Sri Lanka,2,37,31,9,7.16,Colombo,175,89
10231,123,Australia,India,0,30,28,8,6.43,Melbourne,132,92

In [49]:
final_df.drop(columns=['balls_bowled'],inplace=True)

In [50]:
groups = final_df.groupby('match_id')

In [51]:
match_ids = final_df['match_id'].unique()
last_five = []
for id in match_ids:
    last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs_x'].values.tolist())

C:\Users\hp\AppData\Local\Temp\ipykernel_13020\1152253557.py:4: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['batting_team', 'bowling_team', 'city'], dtype='object')
  last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs_x'].values.tolist())

In [52]:
final_df['last_five'] = last_five

In [53]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_five
50264,1542,Bangladesh,Australia,0,32,9,5.65,North Sound,140,86,NaN
87943,2444,Sri Lanka,West Indies,0,5,10,7.50,Mirpur,160,116,NaN
72338,2259,Australia,England,0,2,10,1.50,Melbourne,147,112,NaN
65997,2198,India,New Zealand,0,95,5,6.71,Wellington,149,35,NaN
34429,711,Pakistan,West Indies,0,109,6,7.79,Karachi,172,36,NaN
...,...,...,...,...,...,...,...,...,...,...,...
39540,981,New Zealand,Bangladesh,2,64,9,8.53,Christchurch,208,75,NaN
74367,2279,Sri Lanka,Australia,2,84,8,7.41,Pallekele,198,52,NaN
86880,2433,Sri Lanka,England,1,94,9,7.62,Chittagong,189,46,NaN
91340,2475,Pakistan,Sri Lanka,2,37,9,7.16,Colombo,175,89,NaN
10231,123,Australia,India,0,30,8,6.43,Melbourne,132,92,NaN

In [54]:
final_df.dropna(inplace=True)

In [55]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_five
81367,2360,England,New Zealand,1,1,10,6.00,Auckland,214,119,33.0
1127,15,England,South Africa,0,4,10,3.43,Cardiff,181,113,33.0
83345,2385,South Africa,Sri Lanka,1,56,8,6.59,Hambantota,163,69,32.0
32448,611,Bangladesh,Pakistan,0,2,10,2.00,Dhaka,124,114,28.0
68859,2225,Australia,India,0,178,6,9.45,Barbados,184,7,28.0
...,...,...,...,...,...,...,...,...,...,...,...
49667,1521,Australia,England,1,101,8,10.27,Bridgetown,201,61,43.0
36265,765,India,England,0,62,8,6.10,Adelaide,168,59,40.0
80066,2346,India,Sri Lanka,1,56,9,7.81,Pallekele,155,77,39.0
23588,433,South Africa,Pakistan,1,141,7,9.95,Johannesburg,188,35,40.0
49110,1349,India,Australia,6,29,10,7.91,Bengaluru,160,98,48.0

In [56]:
eligible_cities = final_df['city'].value_counts()[final_df['city'].value_counts() > 600].index.tolist()
final_df = final_df[final_df['city'].isin(eligible_cities)]

In [57]:
X = final_df.drop(columns=['match_id','runs_x','runs_y'])
y = final_df['runs_y']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [58]:
X_test

,batting_team,bowling_team,current_score,wickets_left,crr,city,balls_left,last_five
91853,South Africa,Australia,76,8,9.31,Cape Town,71,48.0
9520,South Africa,Pakistan,158,7,8.17,Johannesburg,4,41.0
2291,West Indies,Pakistan,28,7,4.00,Abu Dhabi,78,32.0
53168,South Africa,West Indies,17,10,4.25,Tarouba,96,26.0
77513,West Indies,Sri Lanka,90,6,5.68,Pallekele,25,47.0
...,...,...,...,...,...,...,...,...
8686,England,Sri Lanka,6,10,12.00,Colombo,117,50.0
18626,Sri Lanka,Pakistan,16,10,8.73,Lahore,109,36.0
72583,New Zealand,Sri Lanka,9,10,5.40,Lauderhill,110,41.0
96214,Sri Lanka,South Africa,47,8,7.83,Delhi,84,32.0
26457,West Indies,Australia,141,7,11.28,Gros Islet,45,42.0

In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

pipe = Pipeline(steps=[
    ('step1', trf),
    ('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

In [69]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9406402808891797
3.7021835528895317

In [76]:
import joblib
joblib.dump(pipe, 'pipe.pkl')  # or whatever file name you're using

['pipe.pkl']